export const ARTISTS_80S = [
  // --- SUPERSTARS & CATALOG ARTISTS (Strings) ---
  "ABBA",
  "AC/DC",
  "Aerosmith",
  "Billy Idol",
  "Billy Joel",
  "Blondie",
  "Bon Jovi",
  "Bruce Springsteen",
  "Bryan Adams",
  "Cher",
  "Chicago",
  "Cindy Lauper",
  "The Clash",
  "Culture Club",
  "David Bowie",
  "Def Leppard",
  "Depeche Mode",
  "Dire Straits",
  "Duran Duran",
  "Elton John",
  "Eurythmics",
  "Fleetwood Mac",
  "Foreigner",
  "Genesis",
  "George Michael",
  "Guns N' Roses",
  "Hall & Oates",
  "Heart",
  "INXS",
  "Iron Maiden",
  "Janet Jackson",
  "Journey",
  "Judas Priest",
  "Kenny Loggins",
  "Kiss",
  "Lionel Richie",
  "Madonna",
  "Michael Jackson",
  "Mötley Crüe",
  "New Order",
  "Olivia Newton-John",
  "Pat Benatar",
  "Pet Shop Boys",
  "Phil Collins",
  "The Police",
  "Prince",
  "Queen",
  "R.E.M.",
  "REO Speedwagon",
  "Rod Stewart",
  "The Rolling Stones",
  "Roxette",
  "Scorpions",
  "Simple Minds",
  "The Smiths",
  "Stevie Wonder",
  "Sting",
  "Talking Heads",
  "Tears for Fears",
  "Tina Turner",
  "Toto",
  "U2",
  "Van Halen",
  "Wham!",
  "Whitney Houston",
  "ZZ Top",

  // --- SPECIFIC HITS, SYNTHPOP & ONE-HIT WONDERS (Objects) ---
  { query: "A-ha Take On Me", title: "Take On Me" },
  { query: "ABC The Look of Love", title: "The Look of Love" },
  { query: "Alphaville Forever Young", title: "Forever Young" },
  { query: "Alphaville Big in Japan", title: "Big in Japan" },
  { query: "The B-52's Love Shack", title: "Love Shack" },
  { query: "Bananarama Venus", title: "Venus" },
  { query: "The Bangles Walk Like an Egyptian", title: "Walk Like an Egyptian" },
  { query: "The Bangles Eternal Flame", title: "Eternal Flame" },
  { query: "Beastie Boys Fight for Your Right", title: "(You Gotta) Fight for Your Right (To Party!)" },
  { query: "Belinda Carlisle Heaven Is a Place on Earth", title: "Heaven Is a Place on Earth" },
  { query: "Berlin Take My Breath Away", title: "Take My Breath Away" },
  { query: "Bill Medley (I've Had) The Time of My Life", title: "(I've Had) The Time of My Life" },
  { query: "Billy Ocean Caribbean Queen", title: "Caribbean Queen" },
  { query: "Bobby McFerrin Don't Worry Be Happy", title: "Don't Worry Be Happy" },
  { query: "Bonnie Tyler Total Eclipse of the Heart", title: "Total Eclipse of the Heart" },
  { query: "Bonnie Tyler Holding Out for a Hero", title: "Holding Out for a Hero" },
  { query: "Boy George Everything I Own", title: "Everything I Own" },
  { query: "Bronski Beat Smalltown Boy", title: "Smalltown Boy" },
  { query: "The Buggles Video Killed the Radio Star", title: "Video Killed the Radio Star" },
  { query: "Cameo Word Up", title: "Word Up!" },
  { query: "The Cars Drive", title: "Drive" },
  { query: "Chaka Khan I Feel for You", title: "I Feel for You" },
  { query: "Cheap Trick The Flame", title: "The Flame" },
  { query: "Chris de Burgh The Lady in Red", title: "The Lady in Red" },
  { query: "Christopher Cross Sailing", title: "Sailing" },
  { query: "The Church Under the Milky Way", title: "Under the Milky Way" },
  { query: "The Communards Don't Leave Me This Way", title: "Don't Leave Me This Way" },
  { query: "Crowded House Don't Dream It's Over", title: "Don't Dream It's Over" },
  { query: "Cutting Crew (I Just) Died in Your Arms", title: "(I Just) Died in Your Arms" },
  { query: "Dead or Alive You Spin Me Round", title: "You Spin Me Round (Like a Record)" },
  { query: "Debbie Gibson Foolish Beat", title: "Foolish Beat" },
  { query: "Deniece Williams Let's Hear It for the Boy", title: "Let's Hear It for the Boy" },
  { query: "Devo Whip It", title: "Whip It" },
  { query: "Dexys Midnight Runners Come On Eileen", title: "Come On Eileen" },
  { query: "Diana Ross I'm Coming Out", title: "I'm Coming Out" },
  { query: "Dionne Warwick That's What Friends Are For", title: "That's What Friends Are For" },
  { query: "Don Henley The Boys of Summer", title: "The Boys of Summer" },
  { query: "Earth, Wind & Fire Let's Groove", title: "Let's Groove" },
  { query: "Eddie Grant Electric Avenue", title: "Electric Avenue" },
  { query: "Eddie Money Take Me Home Tonight", title: "Take Me Home Tonight" },
  { query: "Electric Light Orchestra Don't Bring Me Down", title: "Don't Bring Me Down" },
  { query: "Erasure A Little Respect", title: "A Little Respect" },
  { query: "Europe The Final Countdown", title: "The Final Countdown" },
  { query: "Falco Rock Me Amadeus", title: "Rock Me Amadeus" },
  { query: "Fine Young Cannibals She Drives Me Crazy", title: "She Drives Me Crazy" },
  { query: "A Flock of Seagulls I Ran", title: "I Ran (So Far Away)" },
  { query: "Frankie Goes to Hollywood Relax", title: "Relax" },
  { query: "Frankie Goes to Hollywood The Power of Love", title: "The Power of Love" },
  { query: "Gary Numan Cars", title: "Cars" },
  { query: "Glenn Frey The Heat Is On", title: "The Heat Is On" },
  { query: "Gloria Estefan Conga", title: "Conga" },
  { query: "Harold Faltermeyer Axel F", title: "Axel F" },
  { query: "Herbie Hancock Rockit", title: "Rockit" },
  { query: "The Hooters And We Danced", title: "And We Danced" },
  { query: "Huey Lewis and the News The Power of Love", title: "The Power of Love" },
  { query: "Human League Don't You Want Me", title: "Don't You Want Me" },
  { query: "Irene Cara Flashdance What a Feeling", title: "Flashdance... What a Feeling" },
  { query: "Irene Cara Fame", title: "Fame" },
  { query: "J. Geils Band Centerfold", title: "Centerfold" },
  { query: "Jermaine Stewart We Don't Have to Take Our Clothes Off", title: "We Don't Have to Take Our Clothes Off" },
  { query: "Joan Jett I Love Rock 'n Roll", title: "I Love Rock 'n Roll" },
  { query: "John Farnham You're the Voice", title: "You're the Voice" },
  { query: "John Parr St. Elmo's Fire", title: "St. Elmo's Fire (Man in Motion)" },
  { query: "John Waite Missing You", title: "Missing You" },
  { query: "Joy Division Love Will Tear Us Apart", title: "Love Will Tear Us Apart" },
  { query: "Katrina and the Waves Walking on Sunshine", title: "Walking on Sunshine" },
  { query: "Kenny Rogers Islands in the Stream", title: "Islands in the Stream" },
  { query: "Kim Carnes Bette Davis Eyes", title: "Bette Davis Eyes" },
  { query: "Kim Wilde Kids in America", title: "Kids in America" },
  { query: "Kool & the Gang Celebration", title: "Celebration" },
  { query: "Kraftwerk The Model", title: "The Model" },
  { query: "Kylie Minogue I Should Be So Lucky", title: "I Should Be So Lucky" },
  { query: "Laura Branigan Self Control", title: "Self Control" },
  { query: "Laura Branigan Gloria", title: "Gloria" },
  { query: "Level 42 Lessons in Love", title: "Lessons in Love" },
  { query: "Limahl Never Ending Story", title: "The NeverEnding Story" },
  { query: "Lipps Inc. Funkytown", title: "Funkytown" },
  { query: "Living in a Box Living in a Box", title: "Living in a Box" },
  { query: "Los Lobos La Bamba", title: "La Bamba" },
  { query: "Loverboy Working for the Weekend", title: "Working for the Weekend" },
  { query: "Madness Our House", title: "Our House" },
  { query: "Marvin Gaye Sexual Healing", title: "Sexual Healing" },
  { query: "Matthew Wilder Break My Stride", title: "Break My Stride" },
  { query: "Men at Work Down Under", title: "Down Under" },
  { query: "Men Without Hats The Safety Dance", title: "The Safety Dance" },
  { query: "Miami Sound Machine Dr. Beat", title: "Dr. Beat" },
  { query: "Michael Sembello Maniac", title: "Maniac" },
  { query: "Midnight Oil Beds Are Burning", title: "Beds Are Burning" },
  { query: "Mike + The Mechanics The Living Years", title: "The Living Years" },
  { query: "Modern Talking You're My Heart, You're My Soul", title: "You're My Heart, You're My Soul" },
  { query: "Mr. Mister Broken Wings", title: "Broken Wings" },
  { query: "Murray Head One Night in Bangkok", title: "One Night in Bangkok" },
  { query: "Musical Youth Pass the Dutchie", title: "Pass the Dutchie" },
  { query: "Nena 99 Luftballons", title: "99 Luftballons" },
  { query: "Nik Kershaw The Riddle", title: "The Riddle" },
  { query: "Nik Kershaw I Won't Let the Sun Go Down on Me", title: "I Won't Let the Sun Go Down on Me" },
  { query: "Opus Live Is Life", title: "Live Is Life" },
  { query: "Orchestral Manoeuvres in the Dark Enola Gay", title: "Enola Gay" },
  { query: "The Outfield Your Love", title: "Your Love" },
  { query: "Paul Hardcastle 19", title: "19" },
  { query: "Paul Young Everytime You Go Away", title: "Everytime You Go Away" },
  { query: "Paula Abdul Straight Up", title: "Straight Up" },
  { query: "Peter Gabriel Sledgehammer", title: "Sledgehammer" },
  { query: "Philip Bailey & Phil Collins Easy Lover", title: "Easy Lover" },
  { query: "Pointer Sisters I'm So Excited", title: "I'm So Excited" },
  { query: "The Pretenders Brass in Pocket", title: "Brass in Pocket" },
  { query: "The Proclaimers I'm Gonna Be (500 Miles)", title: "I'm Gonna Be (500 Miles)" },
  { query: "Ray Parker Jr. Ghostbusters", title: "Ghostbusters" },
  { query: "Rick Astley Never Gonna Give You Up", title: "Never Gonna Give You Up" },
  { query: "Rick James Super Freak", title: "Super Freak" },
  { query: "Robert Palmer Addicted to Love", title: "Addicted to Love" },
  { query: "Rockwell Somebody's Watching Me", title: "Somebody's Watching Me" },
  { query: "The Romantics What I Like About You", title: "What I Like About You" },
  { query: "Run-D.M.C. Walk This Way", title: "Walk This Way" },
  { query: "Sabrina Boys (Summertime Love)", title: "Boys (Summertime Love)" },
  { query: "Sade Smooth Operator", title: "Smooth Operator" },
  { query: "Salt-N-Pepa Push It", title: "Push It" },
  { query: "Samantha Fox Touch Me", title: "Touch Me (I Want Your Body)" },
  { query: "Sandra Maria Magdalena", title: "(I'll Never Be) Maria Magdalena" },
  { query: "Shannon Let the Music Play", title: "Let the Music Play" },
  { query: "Sheena Easton 9 to 5", title: "9 to 5 (Morning Train)" },
  { query: "Simply Red Holding Back the Years", title: "Holding Back the Years" },
  { query: "Sister Sledge We Are Family", title: "We Are Family" },
  { query: "Skid Row 18 and Life", title: "18 and Life" },
  { query: "Soft Cell Tainted Love", title: "Tainted Love" },
  { query: "Spandau Ballet True", title: "True" },
  { query: "Spandau Ballet Gold", title: "Gold" },
  { query: "Starship We Built This City", title: "We Built This City" },
  { query: "Status Quo In the Army Now", title: "In the Army Now" },
  { query: "Steve Miller Band Abracadabra", title: "Abracadabra" },
  { query: "Stray Cats Rock This Town", title: "Rock This Town" },
  { query: "Survivor Eye of the Tiger", title: "Eye of the Tiger" },
  { query: "Suzanne Vega Luka", title: "Luka" },
  { query: "Suzanne Vega Tom's Diner", title: "Tom's Diner" },
  { query: "Talk Talk It's My Life", title: "It's My Life" },
  { query: "Taylor Dayne Tell It to My Heart", title: "Tell It to My Heart" },
  { query: "Terence Trent D'Arby Sign Your Name", title: "Sign Your Name" },
  { query: "Tiffany I Think We're Alone Now", title: "I Think We're Alone Now" },
  { query: "Tom Cochrane Life Is a Highway", title: "Life Is a Highway" },
  { query: "Tone Lōc Funky Cold Medina", title: "Funky Cold Medina" },
  { query: "Tracy Chapman Fast Car", title: "Fast Car" },
  { query: "Twisted Sister We're Not Gonna Take It", title: "We're Not Gonna Take It" },
  { query: "UB40 Red Red Wine", title: "Red Red Wine" },
  { query: "Ultravox Vienna", title: "Vienna" },
  { query: "USA for Africa We Are the World", title: "We Are the World" },
  { query: "Vangelis Chariots of Fire", title: "Chariots of Fire" },
  { query: "Violent Femmes Blister in the Sun", title: "Blister in the Sun" },
  { query: "Visage Fade to Grey", title: "Fade to Grey" },
  { query: "Wang Chung Dance Hall Days", title: "Dance Hall Days" },
  { query: "The Weather Girls It's Raining Men", title: "It's Raining Men" },
  { query: "Whitesnake Here I Go Again", title: "Here I Go Again" },
  { query: "Yello Oh Yeah", title: "Oh Yeah" },
  { query: "Yes Owner of a Lonely Heart", title: "Owner of a Lonely Heart" },
  { query: "Young MC Bust A Move", title: "Bust A Move" }
];
export const ARTISTS_ROCK = [
  // --- ROCK LEGENDS & CATALOG ARTISTS (Strings) ---
  "AC/DC",
  "Aerosmith",
  "The Beatles",
  "Billy Idol",
  "Black Sabbath",
  "Bon Jovi",
  "Bruce Springsteen",
  "Bryan Adams",
  "Creedence Clearwater Revival",
  "David Bowie",
  "Deep Purple",
  "Def Leppard",
  "Dire Straits",
  "The Doors",
  "Eagles",
  "Elton John",
  "Eric Clapton",
  "Fleetwood Mac",
  "Foo Fighters",
  "Foreigner",
  "Green Day",
  "Guns N' Roses",
  "Heart",
  "Iron Maiden",
  "Jimi Hendrix",
  "Joan Jett & The Blackhearts",
  "Journey",
  "Judas Priest",
  "KISS",
  "Led Zeppelin",
  "Lynyrd Skynyrd",
  "Metallica",
  "Mötley Crüe",
  "Neil Young",
  "Nirvana",
  "Ozzy Osbourne",
  "Pat Benatar",
  "Pearl Jam",
  "Pink Floyd",
  "The Police",
  "Queen",
  "R.E.M.",
  "Red Hot Chili Peppers",
  "The Rolling Stones",
  "Rush",
  "Scorpions",
  "Soundgarden",
  "Status Quo",
  "Stevie Ray Vaughan",
  "Tom Petty",
  "U2",
  "Van Halen",
  "The Who",
  "ZZ Top",

  // --- ANTHEMS, ONE-HIT WONDERS & SPECIFIC CLASSICS (Objects) ---
  { query: "4 Non Blondes What's Up", title: "What's Up?" },
  { query: "Alice Cooper Poison", title: "Poison" },
  { query: "Alice Cooper School's Out", title: "School's Out" },
  { query: "The Allman Brothers Band Ramblin' Man", title: "Ramblin' Man" },
  { query: "America A Horse With No Name", title: "A Horse With No Name" },
  { query: "The Animals House of the Rising Sun", title: "House of the Rising Sun" },
  { query: "Argent God Gave Rock and Roll to You", title: "God Gave Rock and Roll to You" },
  { query: "Bachman-Turner Overdrive You Ain't Seen Nothing Yet", title: "You Ain't Seen Nothing Yet" },
  { query: "Bad Company Feel Like Makin' Love", title: "Feel Like Makin' Love" },
  { query: "The Band The Weight", title: "The Weight" },
  { query: "Beach Boys Good Vibrations", title: "Good Vibrations" },
  { query: "Bikini Kill Rebel Girl", title: "Rebel Girl" },
  { query: "Blind Melon No Rain", title: "No Rain" },
  { query: "Blue Öyster Cult (Don't Fear) The Reaper", title: "(Don't Fear) The Reaper" },
  { query: "Blur Song 2", title: "Song 2" },
  { query: "Bob Dylan Like a Rolling Stone", title: "Like a Rolling Stone" },
  { query: "Boston More Than a Feeling", title: "More Than a Feeling" },
  { query: "Buffalo Springfield For What It's Worth", title: "For What It's Worth" },
  { query: "The Byrds Mr. Tambourine Man", title: "Mr. Tambourine Man" },
  { query: "Canned Heat On the Road Again", title: "On the Road Again" },
  { query: "Cheap Trick I Want You to Want Me", title: "I Want You to Want Me" },
  { query: "Chicago 25 or 6 to 4", title: "25 or 6 to 4" },
  { query: "The Clash Should I Stay or Should I Go", title: "Should I Stay or Should I Go" },
  { query: "Cream Sunshine of Your Love", title: "Sunshine of Your Love" },
  { query: "The Cult She Sells Sanctuary", title: "She Sells Sanctuary" },
  { query: "Derek and the Dominos Layla", title: "Layla" },
  { query: "Don McLean American Pie", title: "American Pie" },
  { query: "Don Henley The Boys of Summer", title: "The Boys of Summer" },
  { query: "The Doobie Brothers Long Train Runnin'", title: "Long Train Runnin'" },
  { query: "Eddie Money Two Tickets to Paradise", title: "Two Tickets to Paradise" },
  { query: "Electric Light Orchestra Mr. Blue Sky", title: "Mr. Blue Sky" },
  { query: "Europe The Final Countdown", title: "The Final Countdown" },
  { query: "Free All Right Now", title: "All Right Now" },
  { query: "Gary Moore Still Got the Blues", title: "Still Got the Blues" },
  { query: "George Thorogood Bad to the Bone", title: "Bad to the Bone" },
  { query: "Golden Earring Radar Love", title: "Radar Love" },
  { query: "Grand Funk Railroad We're an American Band", title: "We're an American Band" },
  { query: "Grateful Dead Touch of Grey", title: "Touch of Grey" },
  { query: "The Guess Who American Woman", title: "American Woman" },
  { query: "Hollies Long Cool Woman", title: "Long Cool Woman in a Black Dress" },
  { query: "Iggy Pop The Passenger", title: "The Passenger" },
  { query: "Iron Butterfly In-A-Gadda-Da-Vida", title: "In-A-Gadda-Da-Vida" },
  { query: "J. Geils Band Centerfold", title: "Centerfold" },
  { query: "Janis Joplin Me and Bobby McGee", title: "Me and Bobby McGee" },
  { query: "Jefferson Airplane White Rabbit", title: "White Rabbit" },
  { query: "Jethro Tull Aqualung", title: "Aqualung" },
  { query: "Joe Cocker With a Little Help from My Friends", title: "With a Little Help from My Friends" },
  { query: "Joe Walsh Life's Been Good", title: "Life's Been Good" },
  { query: "Kansas Carry On Wayward Son", title: "Carry On Wayward Son" },
  { query: "Kansas Dust in the Wind", title: "Dust in the Wind" },
  { query: "Kingsmen Louie Louie", title: "Louie Louie" },
  { query: "The Kinks You Really Got Me", title: "You Really Got Me" },
  { query: "The Knack My Sharona", title: "My Sharona" },
  { query: "Lenny Kravitz Are You Gonna Go My Way", title: "Are You Gonna Go My Way" },
  { query: "Limp Bizkit Break Stuff", title: "Break Stuff" },
  { query: "Living Colour Cult of Personality", title: "Cult of Personality" },
  { query: "Lou Reed Walk on the Wild Side", title: "Walk on the Wild Side" },
  { query: "Loverboy Working for the Weekend", title: "Working for the Weekend" },
  { query: "Manfred Mann's Earth Band Blinded by the Light", title: "Blinded by the Light" },
  { query: "Meat Loaf Paradise by the Dashboard Light", title: "Paradise by the Dashboard Light" },
  { query: "Midnight Oil Beds Are Burning", title: "Beds Are Burning" },
  { query: "The Moody Blues Nights in White Satin", title: "Nights in White Satin" },
  { query: "Motörhead Ace of Spades", title: "Ace of Spades" },
  { query: "Mott the Hoople All the Young Dudes", title: "All the Young Dudes" },
  { query: "Mountain Mississippi Queen", title: "Mississippi Queen" },
  { query: "Nazareth Love Hurts", title: "Love Hurts" },
  { query: "Norman Greenbaum Spirit in the Sky", title: "Spirit in the Sky" },
  { query: "Oasis Wonderwall", title: "Wonderwall" },
  { query: "The Offspring Self Esteem", title: "Self Esteem" },
  { query: "Peter Frampton Show Me the Way", title: "Show Me the Way" },
  { query: "Procol Harum A Whiter Shade of Pale", title: "A Whiter Shade of Pale" },
  { query: "Queensrÿche Silent Lucidity", title: "Silent Lucidity" },
  { query: "Quiet Riot Cum On Feel the Noize", title: "Cum On Feel the Noize" },
  { query: "Radiohead Creep", title: "Creep" },
  { query: "Rainbow Since You Been Gone", title: "Since You Been Gone" },
  { query: "Ram Jam Black Betty", title: "Black Betty" },
  { query: "Ramones Blitzkrieg Bop", title: "Blitzkrieg Bop" },
  { query: "REO Speedwagon Can't Fight This Feeling", title: "Can't Fight This Feeling" },
  { query: "Santana Smooth", title: "Smooth" },
  { query: "Sex Pistols Anarchy in the UK", title: "Anarchy in the UK" },
  { query: "Shocking Blue Venus", title: "Venus" },
  { query: "Simon & Garfunkel Mrs. Robinson", title: "Mrs. Robinson" },
  { query: "Simple Minds Don't You (Forget About Me)", title: "Don't You (Forget About Me)" },
  { query: "Skid Row 18 and Life", title: "18 and Life" },
  { query: "Slade Cum On Feel the Noize", title: "Cum On Feel the Noize" },
  { query: "Smashing Pumpkins 1979", title: "1979" },
  { query: "Spencer Davis Group Gimme Some Lovin'", title: "Gimme Some Lovin'" },
  { query: "Spin Doctors Two Princes", title: "Two Princes" },
  { query: "Stealers Wheel Stuck in the Middle with You", title: "Stuck in the Middle with You" },
  { query: "Steam Na Na Hey Hey Kiss Him Goodbye", title: "Na Na Hey Hey Kiss Him Goodbye" },
  { query: "Steppenwolf Born to Be Wild", title: "Born to Be Wild" },
  { query: "Steppenwolf Magic Carpet Ride", title: "Magic Carpet Ride" },
  { query: "Steve Miller Band The Joker", title: "The Joker" },
  { query: "Stone Temple Pilots Interstate Love Song", title: "Interstate Love Song" },
  { query: "The Stooges I Wanna Be Your Dog", title: "I Wanna Be Your Dog" },
  { query: "Survivor Eye of the Tiger", title: "Eye of the Tiger" },
  { query: "The Sweet Ballroom Blitz", title: "Ballroom Blitz" },
  { query: "System of a Down Chop Suey!", title: "Chop Suey!" },
  { query: "T. Rex Get It On", title: "Get It On (Bang a Gong)" },
  { query: "Talking Heads Burning Down the House", title: "Burning Down the House" },
  { query: "Ted Nugent Cat Scratch Fever", title: "Cat Scratch Fever" },
  { query: "Ten Years After I'd Love to Change the World", title: "I'd Love to Change the World" },
  { query: "Thin Lizzy The Boys Are Back in Town", title: "The Boys Are Back in Town" },
  { query: "Three Dog Night Joy to the World", title: "Joy to the World" },
  { query: "Toto Africa", title: "Africa" },
  { query: "Toto Hold the Line", title: "Hold the Line" },
  { query: "The Troggs Wild Thing", title: "Wild Thing" },
  { query: "Twisted Sister We're Not Gonna Take It", title: "We're Not Gonna Take It" },
  { query: "Ugly Kid Joe Everything About You", title: "Everything About You" },
  { query: "Uriah Heep Easy Livin'", title: "Easy Livin'" },
  { query: "Van Morrison Brown Eyed Girl", title: "Brown Eyed Girl" },
  { query: "The Velvet Underground Sunday Morning", title: "Sunday Morning" },
  { query: "The Verve Bitter Sweet Symphony", title: "Bitter Sweet Symphony" },
  { query: "War Low Rider", title: "Low Rider" },
  { query: "Warren Zevon Werewolves of London", title: "Werewolves of London" },
  { query: "Whitesnake Here I Go Again", title: "Here I Go Again" },
  { query: "The Yardbirds For Your Love", title: "For Your Love" },
  { query: "Yes Owner of a Lonely Heart", title: "Owner of a Lonely Heart" },
  { query: "The Zombies Time of the Season", title: "Time of the Season" }
];
export const ARTISTS_90S = [
  // --- GIANTS & CATALOG ARTISTS (Strings) ---
  "2Pac",
  "Aerosmith",
  "Alanis Morissette",
  "Alice in Chains",
  "Backstreet Boys",
  "Beastie Boys",
  "Beck",
  "Björk",
  "Blink-182",
  "Blur",
  "Bon Jovi",
  "Boyz II Men",
  "Britney Spears",
  "Bryan Adams",
  "Celine Dion",
  "Christina Aguilera",
  "Daft Punk",
  "Dave Matthews Band",
  "Depeche Mode",
  "Destiny's Child",
  "Dr. Dre",
  "Faith No More",
  "Fatboy Slim",
  "Foo Fighters",
  "Garbage",
  "Green Day",
  "Guns N' Roses",
  "Janet Jackson",
  "Jamiroquai",
  "Jay-Z",
  "Jennifer Lopez",
  "Korn",
  "Lauryn Hill",
  "Lenny Kravitz",
  "Limp Bizkit",
  "Madonna",
  "Mariah Carey",
  "Marilyn Manson",
  "Massive Attack",
  "Metallica",
  "Michael Jackson",
  "Moby",
  "Nas",
  "Nirvana",
  "No Doubt",
  "Notorious B.I.G.",
  "NSYNC",
  "Oasis",
  "Pearl Jam",
  "Pet Shop Boys",
  "Portishead",
  "Prince",
  "Prodigy, The",
  "Puff Daddy",
  "Pulp",
  "R.E.M.",
  "Radiohead",
  "Rage Against the Machine",
  "Red Hot Chili Peppers",
  "Ricky Martin",
  "Robbie Williams",
  "Roxette",
  "Savage Garden",
  "Shania Twain",
  "Sheryl Crow",
  "Smashing Pumpkins, The",
  "Snoop Dogg",
  "Soundgarden",
  "Spice Girls",
  "Stone Temple Pilots",
  "Suede",
  "TLC",
  "The Chemical Brothers",
  "The Cranberries",
  "The Offspring",
  "U2",
  "Weezer",
  "Whitney Houston",
  "Will Smith",

  // --- SPECIFIC HITS, ANTHEMS & EURODANCE (Objects) ---
  { query: "4 Non Blondes What's Up", title: "What's Up?" },
  { query: "Ace of Base All That She Wants", title: "All That She Wants" },
  { query: "Ace of Base The Sign", title: "The Sign" },
  { query: "Adamski Killer", title: "Killer" },
  { query: "All-4-One I Swear", title: "I Swear" },
  { query: "Annie Lennox No More I Love Yous", title: "No More 'I Love You's'" },
  { query: "Aqua Barbie Girl", title: "Barbie Girl" },
  { query: "Aqua Doctor Jones", title: "Doctor Jones" },
  { query: "Army of Lovers Crucified", title: "Crucified" },
  { query: "Babylon Zoo Spaceman", title: "Spaceman" },
  { query: "Barenaked Ladies One Week", title: "One Week" },
  { query: "Bell Biv DeVoe Poison", title: "Poison" },
  { query: "Billie Myers Kiss the Rain", title: "Kiss the Rain" },
  { query: "Blackstreet No Diggity", title: "No Diggity" },
  { query: "Blind Melon No Rain", title: "No Rain" },
  { query: "Bloodhound Gang The Bad Touch", title: "The Bad Touch" },
  { query: "Bush Glycerine", title: "Glycerine" },
  { query: "C+C Music Factory Gonna Make You Sweat", title: "Gonna Make You Sweat" },
  { query: "Cardigans Lovefool", title: "Lovefool" },
  { query: "Cardigans My Favourite Game", title: "My Favourite Game" },
  { query: "Charles & Eddie Would I Lie to You", title: "Would I Lie to You?" },
  { query: "Cher Believe", title: "Believe" },
  { query: "Chumbawamba Tubthumping", title: "Tubthumping" },
  { query: "Coolio Gangsta's Paradise", title: "Gangsta's Paradise" },
  { query: "Corona The Rhythm of the Night", title: "The Rhythm of the Night" },
  { query: "Counting Crows Mr. Jones", title: "Mr. Jones" },
  { query: "Crash Test Dummies Mmm Mmm Mmm Mmm", title: "Mmm Mmm Mmm Mmm" },
  { query: "Culture Beat Mr. Vain", title: "Mr. Vain" },
  { query: "Cypress Hill Insane in the Brain", title: "Insane in the Brain" },
  { query: "Deep Blue Something Breakfast at Tiffany's", title: "Breakfast at Tiffany's" },
  { query: "Deee-Lite Groove Is in the Heart", title: "Groove Is in the Heart" },
  { query: "Des'ree You Gotta Be", title: "You Gotta Be" },
  { query: "Divinyls I Touch Myself", title: "I Touch Myself" },
  { query: "DNA Suzanne Vega Tom's Diner", title: "Tom's Diner" },
  { query: "Dr. Alban It's My Life", title: "It's My Life" },
  { query: "Duran Duran Ordinary World", title: "Ordinary World" },
  { query: "Eagle-Eye Cherry Save Tonight", title: "Save Tonight" },
  { query: "Eels Novocaine for the Soul", title: "Novocaine for the Soul" },
  { query: "Eiffel 65 Blue Da Ba Dee", title: "Blue (Da Ba Dee)" },
  { query: "EMF Unbelievable", title: "Unbelievable" },
  { query: "En Vogue Don't Let Go", title: "Don't Let Go (Love)" },
  { query: "Enigma Sadeness", title: "Sadeness (Part I)" },
  { query: "Eric Clapton Tears in Heaven", title: "Tears in Heaven" },
  { query: "Everything But The Girl Missing", title: "Missing (Todd Terry Remix)" },
  { query: "Extreme More Than Words", title: "More Than Words" },
  { query: "Faithless Insomnia", title: "Insomnia" },
  { query: "Fugees Killing Me Softly", title: "Killing Me Softly With His Song" },
  { query: "Gala Freed from Desire", title: "Freed from Desire" },
  { query: "George Michael Freedom 90", title: "Freedom! '90" },
  { query: "Gin Blossoms Hey Jealousy", title: "Hey Jealousy" },
  { query: "Goo Goo Dolls Iris", title: "Iris" },
  { query: "Groove Armada At the River", title: "At the River" },
  { query: "Haddaway What Is Love", title: "What Is Love" },
  { query: "Hanson MMMBop", title: "MMMBop" },
  { query: "Hole Violet", title: "Violet" },
  { query: "House of Pain Jump Around", title: "Jump Around" },
  { query: "Ini Kamoze Here Comes the Hotstepper", title: "Here Comes the Hotstepper" },
  { query: "Inner Circle Bad Boys", title: "Bad Boys" },
  { query: "Inner Circle Sweat", title: "Sweat (A La La La La Long)" },
  { query: "Jane's Addiction Been Caught Stealing", title: "Been Caught Stealing" },
  { query: "Joan Osborne One of Us", title: "One of Us" },
  { query: "K's Choice Not An Addict", title: "Not An Addict" },
  { query: "Kris Kross Jump", title: "Jump" },
  { query: "Lisa Loeb Stay", title: "Stay (I Missed You)" },
  { query: "Live Lightning Crashes", title: "Lightning Crashes" },
  { query: "Londonbeat I've Been Thinking About You", title: "I've Been Thinking About You" },
  { query: "Los Del Rio Macarena", title: "Macarena" },
  { query: "Lou Bega Mambo No. 5", title: "Mambo No. 5" },
  { query: "Luniz I Got 5 On It", title: "I Got 5 On It" },
  { query: "M.C. Hammer U Can't Touch This", title: "U Can't Touch This" },
  { query: "Manic Street Preachers A Design for Life", title: "A Design for Life" },
  { query: "Marc Cohn Walking in Memphis", title: "Walking in Memphis" },
  { query: "Mark Morrison Return of the Mack", title: "Return of the Mack" },
  { query: "Matchbox Twenty Push", title: "Push" },
  { query: "Mazzy Star Fade Into You", title: "Fade Into You" },
  { query: "Meat Loaf I'd Do Anything for Love", title: "I'd Do Anything for Love" },
  { query: "Meredith Brooks Bitch", title: "Bitch" },
  { query: "Montell Jordan This Is How We Do It", title: "This Is How We Do It" },
  { query: "Mr. Big To Be With You", title: "To Be With You" },
  { query: "Natalie Imbruglia Torn", title: "Torn" },
  { query: "New Radicals You Get What You Give", title: "You Get What You Give" },
  { query: "Nick Cave Where the Wild Roses Grow", title: "Where the Wild Roses Grow" },
  { query: "OMC How Bizarre", title: "How Bizarre" },
  { query: "Placebo Every You Every Me", title: "Every You Every Me" },
  { query: "Presidents of the United States of America Peaches", title: "Peaches" },
  { query: "Primal Scream Rocks", title: "Rocks" },
  { query: "Rednex Cotton Eye Joe", title: "Cotton Eye Joe" },
  { query: "Republica Ready to Go", title: "Ready to Go" },
  { query: "Right Said Fred I'm Too Sexy", title: "I'm Too Sexy" },
  { query: "Robyn Show Me Love", title: "Show Me Love" },
  { query: "Salt-N-Pepa Shoop", title: "Shoop" },
  { query: "Santana Smooth", title: "Smooth" },
  { query: "Sash! Encore Une Fois", title: "Encore Une Fois" },
  { query: "Scatman John Scatman", title: "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)" },
  { query: "Seal Kiss from a Rose", title: "Kiss from a Rose" },
  { query: "Semisonic Closing Time", title: "Closing Time" },
  { query: "Shaggy Boombastic", title: "Boombastic" },
  { query: "Sinead O'Connor Nothing Compares 2 U", title: "Nothing Compares 2 U" },
  { query: "Sir Mix-A-Lot Baby Got Back", title: "Baby Got Back" },
  { query: "Sixpence None the Richer Kiss Me", title: "Kiss Me" },
  { query: "Smash Mouth All Star", title: "All Star" },
  { query: "Snap! Rhythm is a Dancer", title: "Rhythm is a Dancer" },
  { query: "Snow Informer", title: "Informer" },
  { query: "Soft Cell Tainted Love", title: "Tainted Love ('91 Remix)" },
  { query: "Soul Asylum Runaway Train", title: "Runaway Train" },
  { query: "Spacehog In the Meantime", title: "In the Meantime" },
  { query: "Spin Doctors Two Princes", title: "Two Princes" },
  { query: "Stereo MC's Connected", title: "Connected" },
  { query: "Sublime Santeria", title: "Santeria" },
  { query: "Sugar Ray Fly", title: "Fly" },
  { query: "Supergrass Alright", title: "Alright" },
  { query: "Tag Team Whoomp There It Is", title: "Whoomp! (There It Is)" },
  { query: "Take That Back for Good", title: "Back for Good" },
  { query: "Tal Bachman She's So High", title: "She's So High" },
  { query: "Tasmin Archer Sleeping Satellite", title: "Sleeping Satellite" },
  { query: "The Cardigans My Favourite Game", title: "My Favourite Game" },
  { query: "The Connells '74-'75", title: "'74-'75" },
  { query: "The Cure Friday I'm in Love", title: "Friday I'm in Love" },
  { query: "The La's There She Goes", title: "There She Goes" },
  { query: "The Rembrandts I'll Be There for You", title: "I'll Be There for You" },
  { query: "The Verve Bitter Sweet Symphony", title: "Bitter Sweet Symphony" },
  { query: "Third Eye Blind Semi-Charmed Life", title: "Semi-Charmed Life" },
  { query: "Tom Cochrane Life Is a Highway", title: "Life Is a Highway" },
  { query: "Toploader Dancing in the Moonlight", title: "Dancing in the Moonlight" },
  { query: "Ugly Kid Joe Everything About You", title: "Everything About You" },
  { query: "Underworld Born Slippy", title: "Born Slippy .NUXX" },
  { query: "Urban Cookie Collective The Key the Secret", title: "The Key the Secret" },
  { query: "Vanilla Ice Ice Ice Baby", title: "Ice Ice Baby" },
  { query: "Vengaboys Boom Boom Boom Boom", title: "Boom, Boom, Boom, Boom!!" },
  { query: "Vengaboys We're Going to Ibiza", title: "We're Going to Ibiza!" },
  { query: "Wallflowers One Headlight", title: "One Headlight" },
  { query: "Warren G Regulate", title: "Regulate" },
  { query: "Wet Wet Wet Love Is All Around", title: "Love Is All Around" },
  { query: "Whale Hobo Humpin' Slobo Babe", title: "Hobo Humpin' Slobo Babe" },
  { query: "Wheatus Teenage Dirtbag", title: "Teenage Dirtbag" },
  { query: "Whigfield Saturday Night", title: "Saturday Night" },
  { query: "White Town Your Woman", title: "Your Woman" },
  { query: "Youssou N'Dour 7 Seconds", title: "7 Seconds" }
];
export const ARTISTS_2000S = [
  // --- SUPERSTARS & CATALOG ARTISTS (Strings) ---
  "50 Cent",
  "Akon",
  "Alicia Keys",
  "Amy Winehouse",
  "Avril Lavigne",
  "Beyoncé",
  "Black Eyed Peas",
  "Blink-182",
  "Britney Spears",
  "Chris Brown",
  "Christina Aguilera",
  "Coldplay",
  "Daft Punk",
  "Destiny's Child",
  "Eminem",
  "Enrique Iglesias",
  "Evanescence",
  "Fall Out Boy",
  "Foo Fighters",
  "Gorillaz",
  "Green Day",
  "Gwen Stefani",
  "Jay-Z",
  "Jennifer Lopez",
  "Justin Timberlake",
  "Kanye West",
  "Katy Perry",
  "Kelly Clarkson",
  "Lady Gaga",
  "Linkin Park",
  "Madonna",
  "Maroon 5",
  "Muse",
  "Nelly",
  "Nelly Furtado",
  "Nickelback",
  "No Doubt",
  "OutKast",
  "P!nk",
  "Paramore",
  "Queens of the Stone Age",
  "Red Hot Chili Peppers",
  "Rihanna",
  "Robbie Williams",
  "Sean Paul",
  "Shakira",
  "System of a Down",
  "The Killers",
  "Usher",
  "Westlife",

  // --- SPECIFIC HITS, ANTHEMS & ONE-HIT WONDERS (Objects) ---
  { query: "3 Doors Down Kryptonite", title: "Kryptonite" },
  { query: "30 Seconds to Mars The Kill", title: "The Kill" },
  { query: "Aaliyah Try Again", title: "Try Again" },
  { query: "Afroman Because I Got High", title: "Because I Got High" },
  { query: "Alcazar Crying at the Discotheque", title: "Crying at the Discotheque" },
  { query: "Alien Ant Farm Smooth Criminal", title: "Smooth Criminal" },
  { query: "All-American Rejects Gives You Hell", title: "Gives You Hell" },
  { query: "Anastacia I'm Outta Love", title: "I'm Outta Love" },
  { query: "Andrew W.K. Party Hard", title: "Party Hard" },
  { query: "Arctic Monkeys I Bet You Look Good On The Dancefloor", title: "I Bet You Look Good On The Dancefloor" },
  { query: "Ashanti Foolish", title: "Foolish" },
  { query: "Atomic Kitten The Tide Is High", title: "The Tide Is High" },
  { query: "Audioslave Like a Stone", title: "Like a Stone" },
  { query: "Baha Men Who Let the Dogs Out", title: "Who Let the Dogs Out" },
  { query: "Basshunter Boten Anna", title: "Boten Anna" },
  { query: "Benny Benassi Satisfaction", title: "Satisfaction" },
  { query: "Bloc Party Banquet", title: "Banquet" },
  { query: "Bloodhound Gang The Bad Touch", title: "The Bad Touch" },
  { query: "Blu Cantrell Hit 'Em Up Style", title: "Hit 'Em Up Style (Oops!)" },
  { query: "Bob Sinclar Love Generation", title: "Love Generation" },
  { query: "Bon Jovi It's My Life", title: "It's My Life" },
  { query: "Bowling for Soup 1985", title: "1985" },
  { query: "Busted Year 3000", title: "Year 3000" },
  { query: "Caesars Jerk It Out", title: "Jerk It Out" },
  { query: "Carrie Underwood Before He Cheats", title: "Before He Cheats" },
  { query: "Cascada Everytime We Touch", title: "Everytime We Touch" },
  { query: "Chamillionaire Ridin'", title: "Ridin'" },
  { query: "Chemical Brothers Galvanize", title: "Galvanize" },
  { query: "Ciara 1 2 Step", title: "1, 2 Step" },
  { query: "Colbie Caillat Bubbly", title: "Bubbly" },
  { query: "Corinne Bailey Rae Put Your Records On", title: "Put Your Records On" },
  { query: "Crazy Town Butterfly", title: "Butterfly" },
  { query: "Creed With Arms Wide Open", title: "With Arms Wide Open" },
  { query: "Daddy Yankee Gasolina", title: "Gasolina" },
  { query: "Daniel Powter Bad Day", title: "Bad Day" },
  { query: "Darude Sandstorm", title: "Sandstorm" },
  { query: "Daughtry It's Not Over", title: "It's Not Over" },
  { query: "Dido White Flag", title: "White Flag" },
  { query: "Disturbed Down with the Sickness", title: "Down with the Sickness" },
  { query: "DJ Casper Cha Cha Slide", title: "Cha Cha Slide" },
  { query: "DJ Ötzi Hey Baby", title: "Hey Baby" },
  { query: "Duffy Mercy", title: "Mercy" },
  { query: "Electric Six Danger! High Voltage", title: "Danger! High Voltage" },
  { query: "Eric Prydz Call on Me", title: "Call on Me" },
  { query: "Eve Let Me Blow Ya Mind", title: "Let Me Blow Ya Mind" },
  { query: "Fergie Big Girls Don't Cry", title: "Big Girls Don't Cry" },
  { query: "Five for Fighting Superman", title: "Superman (It's Not Easy)" },
  { query: "Flo Rida Low", title: "Low" },
  { query: "Florence + The Machine Dog Days Are Over", title: "Dog Days Are Over" },
  { query: "Fountains of Wayne Stacy's Mom", title: "Stacy's Mom" },
  { query: "Franz Ferdinand Take Me Out", title: "Take Me Out" },
  { query: "Gavin DeGraw I Don't Want to Be", title: "I Don't Want to Be" },
  { query: "Gnarls Barkley Crazy", title: "Crazy" },
  { query: "Good Charlotte Lifestyles of the Rich & Famous", title: "Lifestyles of the Rich & Famous" },
  { query: "Gossip Heavy Cross", title: "Heavy Cross" },
  { query: "Gym Class Heroes Cupid's Chokehold", title: "Cupid's Chokehold" },
  { query: "Hellacopters By the Grace of God", title: "By the Grace of God" },
  { query: "HIM Join Me in Death", title: "Join Me in Death" },
  { query: "Hives Hate to Say I Told You So", title: "Hate to Say I Told You So" },
  { query: "Hoobastank The Reason", title: "The Reason" },
  { query: "James Blunt You're Beautiful", title: "You're Beautiful" },
  { query: "Jason Mraz I'm Yours", title: "I'm Yours" },
  { query: "Jet Are You Gonna Be My Girl", title: "Are You Gonna Be My Girl" },
  { query: "Jimmy Eat World The Middle", title: "The Middle" },
  { query: "John Mayer Waiting on the World to Change", title: "Waiting on the World to Change" },
  { query: "Just Jack Starz in Their Eyes", title: "Starz in Their Eyes" },
  { query: "Justice D.A.N.C.E.", title: "D.A.N.C.E." },
  { query: "Kaiser Chiefs Ruby", title: "Ruby" },
  { query: "Keane Somewhere Only We Know", title: "Somewhere Only We Know" },
  { query: "Kevin Lyttle Turn Me On", title: "Turn Me On" },
  { query: "Kid Cudi Day 'N' Nite", title: "Day 'N' Nite" },
  { query: "Kid Rock All Summer Long", title: "All Summer Long" },
  { query: "Kings of Leon Sex on Fire", title: "Sex on Fire" },
  { query: "Kylie Minogue Can't Get You Out of My Head", title: "Can't Get You Out of My Head" },
  { query: "La Roux Bulletproof", title: "Bulletproof" },
  { query: "Las Ketchup The Ketchup Song", title: "The Ketchup Song (Aserejé)" },
  { query: "LeAnn Rimes Can't Fight the Moonlight", title: "Can't Fight the Moonlight" },
  { query: "Leona Lewis Bleeding Love", title: "Bleeding Love" },
  { query: "Lifehouse Hanging by a Moment", title: "Hanging by a Moment" },
  { query: "Lily Allen Smile", title: "Smile" },
  { query: "Limp Bizkit Rollin'", title: "Rollin'" },
  { query: "M.I.A. Paper Planes", title: "Paper Planes" },
  { query: "Macy Gray I Try", title: "I Try" },
  { query: "Mary J. Blige Family Affair", title: "Family Affair" },
  { query: "MGMT Kids", title: "Kids" },
  { query: "Mika Grace Kelly", title: "Grace Kelly" },
  { query: "Missy Elliott Work It", title: "Work It" },
  { query: "Modjo Lady Hear Me Tonight", title: "Lady (Hear Me Tonight)" },
  { query: "My Chemical Romance Welcome to the Black Parade", title: "Welcome to the Black Parade" },
  { query: "Natasha Bedingfield Unwritten", title: "Unwritten" },
  { query: "Ne-Yo So Sick", title: "So Sick" },
  { query: "Norah Jones Don't Know Why", title: "Don't Know Why" },
  { query: "O-Zone Dragostea Din Tei", title: "Dragostea Din Tei" },
  { query: "OneRepublic Apologize", title: "Apologize" },
  { query: "Owl City Fireflies", title: "Fireflies" },
  { query: "Panic! At The Disco I Write Sins Not Tragedies", title: "I Write Sins Not Tragedies" },
  { query: "Papa Roach Last Resort", title: "Last Resort" },
  { query: "Peter Bjorn and John Young Folks", title: "Young Folks" },
  { query: "Phantom Planet California", title: "California" },
  { query: "Phoenix 1901", title: "1901" },
  { query: "Plain White T's Hey There Delilah", title: "Hey There Delilah" },
  { query: "Pussycat Dolls Don't Cha", title: "Don't Cha" },
  { query: "Rasmus In the Shadows", title: "In the Shadows" },
  { query: "Razorlight America", title: "America" },
  { query: "Ricky Martin She Bangs", title: "She Bangs" },
  { query: "Safri Duo Played-A-Live", title: "Played-A-Live (The Bongo Song)" },
  { query: "Santana Maria Maria", title: "Maria Maria" },
  { query: "Sara Bareilles Love Song", title: "Love Song" },
  { query: "Scissor Sisters I Don't Feel Like Dancin'", title: "I Don't Feel Like Dancin'" },
  { query: "Shaggy It Wasn't Me", title: "It Wasn't Me" },
  { query: "Shania Twain I'm Gonna Getcha Good!", title: "I'm Gonna Getcha Good!" },
  { query: "Sisqó Thong Song", title: "Thong Song" },
  { query: "Smash Mouth I'm a Believer", title: "I'm a Believer" },
  { query: "Snow Patrol Chasing Cars", title: "Chasing Cars" },
  { query: "Sophie Ellis-Bextor Murder on the Dancefloor", title: "Murder on the Dancefloor" },
  { query: "Soulja Boy Crank That", title: "Crank That (Soulja Boy)" },
  { query: "Strokes Last Nite", title: "Last Nite" },
  { query: "Sugababes Push the Button", title: "Push the Button" },
  { query: "Sum 41 Fat Lip", title: "Fat Lip" },
  { query: "T.I. Live Your Life", title: "Live Your Life" },
  { query: "t.A.T.u. All the Things She Said", title: "All the Things She Said" },
  { query: "Take That Patience", title: "Patience" },
  { query: "Teddybears Cobrastyle", title: "Cobrastyle" },
  { query: "Tenacious D Tribute", title: "Tribute" },
  { query: "The Calling Wherever You Will Go", title: "Wherever You Will Go" },
  { query: "The Darkness I Believe in a Thing Called Love", title: "I Believe in a Thing Called Love" },
  { query: "The Fray How to Save a Life", title: "How to Save a Life" },
  { query: "The Kooks Naive", title: "Naive" },
  { query: "The White Stripes Seven Nation Army", title: "Seven Nation Army" },
  { query: "Timbaland The Way I Are", title: "The Way I Are" },
  { query: "Ting Tings That's Not My Name", title: "That's Not My Name" },
  { query: "Tokio Hotel Monsoon", title: "Monsoon" },
  { query: "Train Drops of Jupiter", title: "Drops of Jupiter" },
  { query: "Travis Sing", title: "Sing" },
  { query: "U2 Beautiful Day", title: "Beautiful Day" },
  { query: "Uncle Kracker Follow Me", title: "Follow Me" },
  { query: "Vampire Weekend A-Punk", title: "A-Punk" },
  { query: "Vanessa Carlton A Thousand Miles", title: "A Thousand Miles" },
  { query: "Wheatus Teenage Dirtbag", title: "Teenage Dirtbag" },
  { query: "Wolfmother Woman", title: "Woman" },
  { query: "Wombats Let's Dance to Joy Division", title: "Let's Dance to Joy Division" },
  { query: "Yeah Yeah Yeahs Heads Will Roll", title: "Heads Will Roll" },
  { query: "Yellowcard Ocean Avenue", title: "Ocean Avenue" }
];
export const ARTISTS_2010S = [
  // --- SUPERSTARS & CATALOG ARTISTS (Strings) ---
  // Dessa artister har så många hits att man kan spela nästan vad som helst.
  "Adele",
  "Ariana Grande",
  "Avicii",
  "Beyoncé",
  "Billie Eilish",
  "Bruno Mars",
  "Calvin Harris",
  "Cardi B",
  "Coldplay",
  "David Guetta",
  "Drake",
  "Dua Lipa",
  "Ed Sheeran",
  "Ellie Goulding",
  "Eminem",
  "Florence + The Machine",
  "Halsey",
  "Imagine Dragons",
  "J. Cole",
  "Jason Derulo",
  "Justin Bieber",
  "Katy Perry",
  "Kendrick Lamar",
  "Khalid",
  "Kygo",
  "Lady Gaga",
  "Lana Del Rey",
  "Little Mix",
  "Lorde",
  "Macklemore & Ryan Lewis",
  "Maroon 5",
  "Marshmello",
  "Miley Cyrus",
  "Mumford & Sons",
  "Nicki Minaj",
  "One Direction",
  "P!nk",
  "Pitbull",
  "Post Malone",
  "Rihanna",
  "Sam Smith",
  "Selena Gomez",
  "Shawn Mendes",
  "Sia",
  "Taylor Swift",
  "The Chainsmokers",
  "The Weeknd",
  "Twenty One Pilots",
  "Zara Larsson",
  "Zedd",

  // --- SPECIFIC HITS, VIRAL TRENDS & ANTHEMS (Objects) ---
  // Specifika låtar för att fånga one-hit wonders eller definierande hits.
  { query: "5 Seconds of Summer She Looks So Perfect", title: "She Looks So Perfect" },
  { query: "Alan Walker Faded", title: "Faded" },
  { query: "Alessia Cara Here", title: "Here" },
  { query: "Alex Clare Too Close", title: "Too Close" },
  { query: "Aloe Blacc I Need a Dollar", title: "I Need a Dollar" },
  { query: "American Authors Best Day of My Life", title: "Best Day of My Life" },
  { query: "Andy Grammer Honey, I'm Good", title: "Honey, I'm Good" },
  { query: "Anna Kendrick Cups", title: "Cups (Pitch Perfect's When I'm Gone)" },
  { query: "AWOLNATION Sail", title: "Sail" },
  { query: "Azealia Banks 212", title: "212" },
  { query: "Baauer Harlem Shake", title: "Harlem Shake" },
  { query: "Bastille Pompeii", title: "Pompeii" },
  { query: "Bebe Rexha Meant to Be", title: "Meant to Be" },
  { query: "Black Keys Lonely Boy", title: "Lonely Boy" },
  { query: "Blake Shelton God's Country", title: "God's Country" },
  { query: "Carly Rae Jepsen Call Me Maybe", title: "Call Me Maybe" },
  { query: "Capital Cities Safe and Sound", title: "Safe and Sound" },
  { query: "Camila Cabello Havana", title: "Havana" },
  { query: "Charlie Puth See You Again", title: "See You Again" },
  { query: "Charli XCX Boom Clap", title: "Boom Clap" },
  { query: "Childish Gambino This Is America", title: "This Is America" },
  { query: "Clean Bandit Rather Be", title: "Rather Be" },
  { query: "Clean Bandit Rockabye", title: "Rockabye" },
  { query: "Daft Punk Get Lucky", title: "Get Lucky" },
  { query: "Dawin Dessert", title: "Dessert" },
  { query: "Demi Lovato Sorry Not Sorry", title: "Sorry Not Sorry" },
  { query: "Desiigner Panda", title: "Panda" },
  { query: "Disclosure Latch", title: "Latch" },
  { query: "DJ Snake Turn Down for What", title: "Turn Down for What" },
  { query: "DJ Snake Taki Taki", title: "Taki Taki" },
  { query: "DNCE Cake by the Ocean", title: "Cake by the Ocean" },
  { query: "D.R.A.M. Broccoli", title: "Broccoli" },
  { query: "Edward Maya Stereo Love", title: "Stereo Love" },
  { query: "Empire of the Sun Walking On A Dream", title: "Walking On A Dream" },
  { query: "Far East Movement Like a G6", title: "Like a G6" },
  { query: "Fetty Wap Trap Queen", title: "Trap Queen" },
  { query: "Fifth Harmony Work from Home", title: "Work from Home" },
  { query: "Fitz and the Tantrums HandClap", title: "HandClap" },
  { query: "Florida Georgia Line Cruise", title: "Cruise" },
  { query: "Foster the People Pumped Up Kicks", title: "Pumped Up Kicks" },
  { query: "French Montana Unforgettable", title: "Unforgettable" },
  { query: "Fun. We Are Young", title: "We Are Young" },
  { query: "Fun. Some Nights", title: "Some Nights" },
  { query: "Galantis Runaway (U & I)", title: "Runaway (U & I)" },
  { query: "George Ezra Budapest", title: "Budapest" },
  { query: "Gotye Somebody That I Used to Know", title: "Somebody That I Used to Know" },
  { query: "Hailee Steinfeld Starving", title: "Starving" },
  { query: "Harry Styles Sign of the Times", title: "Sign of the Times" },
  { query: "Hozier Take Me to Church", title: "Take Me to Church" },
  { query: "Icona Pop I Love It", title: "I Love It" },
  { query: "Idina Menzel Let It Go", title: "Let It Go (Frozen)" },
  { query: "Iggy Azalea Fancy", title: "Fancy" },
  { query: "James Arthur Say You Won't Let Go", title: "Say You Won't Let Go" },
  { query: "Jay-Z Kanye West Niggas in Paris", title: "Ni**as in Paris" },
  { query: "Jeremih Don't Tell 'Em", title: "Don't Tell 'Em" },
  { query: "Jessie J Price Tag", title: "Price Tag" },
  { query: "John Legend All of Me", title: "All of Me" },
  { query: "Jonas Brothers Sucker", title: "Sucker" },
  { query: "Justin Timberlake Can't Stop the Feeling", title: "Can't Stop the Feeling!" },
  { query: "Kesha TiK ToK", title: "TiK ToK" },
  { query: "Kungs This Girl", title: "This Girl" },
  { query: "Labrinth Jealous", title: "Jealous" },
  { query: "Lewis Capaldi Someone You Loved", title: "Someone You Loved" },
  { query: "Lil Nas X Old Town Road", title: "Old Town Road" },
  { query: "Lil Pump Gucci Gang", title: "Gucci Gang" },
  { query: "Lizzo Truth Hurts", title: "Truth Hurts" },
  { query: "LMFAO Party Rock Anthem", title: "Party Rock Anthem" },
  { query: "LMFAO Sexy and I Know It", title: "Sexy and I Know It" },
  { query: "Logic 1-800-273-8255", title: "1-800-273-8255" },
  { query: "Luis Fonsi Despacito", title: "Despacito" },
  { query: "Lukas Graham 7 Years", title: "7 Years" },
  { query: "Lumineers Ho Hey", title: "Ho Hey" },
  { query: "M83 Midnight City", title: "Midnight City" },
  { query: "Magic! Rude", title: "Rude" },
  { query: "Major Lazer Lean On", title: "Lean On" },
  { query: "Mark Ronson Uptown Funk", title: "Uptown Funk" },
  { query: "Martin Garrix Animals", title: "Animals" },
  { query: "Meghan Trainor All About That Bass", title: "All About That Bass" },
  { query: "Michael Kiwanuka Cold Little Heart", title: "Cold Little Heart" },
  { query: "Migos Bad and Boujee", title: "Bad and Boujee" },
  { query: "Mike Posner I Took a Pill in Ibiza", title: "I Took a Pill in Ibiza (Seeb Remix)" },
  { query: "Milky Chance Stolen Dance", title: "Stolen Dance" },
  { query: "MKTO Classic", title: "Classic" },
  { query: "Nico & Vinz Am I Wrong", title: "Am I Wrong" },
  { query: "Of Monsters and Men Little Talks", title: "Little Talks" },
  { query: "OMI Cheerleader", title: "Cheerleader (Felix Jaehn Remix)" },
  { query: "OneRepublic Counting Stars", title: "Counting Stars" },
  { query: "Owl City Fireflies", title: "Fireflies" },
  { query: "Panic! At The Disco High Hopes", title: "High Hopes" },
  { query: "Passenger Let Her Go", title: "Let Her Go" },
  { query: "Pharrell Williams Happy", title: "Happy" },
  { query: "Philip George Wish You Were Mine", title: "Wish You Were Mine" },
  { query: "Portugal. The Man Feel It Still", title: "Feel It Still" },
  { query: "Psy Gangnam Style", title: "Gangnam Style" },
  { query: "Rachel Platten Fight Song", title: "Fight Song" },
  { query: "Rae Sremmurd Black Beatles", title: "Black Beatles" },
  { query: "Rag'n'Bone Man Human", title: "Human" },
  { query: "Robin Thicke Blurred Lines", title: "Blurred Lines" },
  { query: "Robyn Dancing On My Own", title: "Dancing On My Own" },
  { query: "Rudimental Waiting All Night", title: "Waiting All Night" },
  { query: "Sak Noel Loca People", title: "Loca People" },
  { query: "Silentó Watch Me", title: "Watch Me (Whip/Nae Nae)" },
  { query: "Skrillex Bangarang", title: "Bangarang" },
  { query: "Stromae Alors on danse", title: "Alors on danse" },
  { query: "Swedish House Mafia Don't You Worry Child", title: "Don't You Worry Child" },
  { query: "Taio Cruz Dynamite", title: "Dynamite" },
  { query: "Tame Impala The Less I Know the Better", title: "The Less I Know the Better" },
  { query: "The Greatest Showman This Is Me", title: "This Is Me" },
  { query: "Tones and I Dance Monkey", title: "Dance Monkey" },
  { query: "Tove Lo Habits", title: "Habits (Stay High)" },
  { query: "Train Hey Soul Sister", title: "Hey, Soul Sister" },
  { query: "Travie McCoy Billionaire", title: "Billionaire" },
  { query: "Tyga Rack City", title: "Rack City" },
  { query: "Vance Joy Riptide", title: "Riptide" },
  { query: "Walk the Moon Shut Up and Dance", title: "Shut Up and Dance" },
  { query: "Wiz Khalifa Black and Yellow", title: "Black and Yellow" },
  { query: "Wiz Khalifa See You Again", title: "See You Again" },
  { query: "X Ambassadors Renegades", title: "Renegades" },
  { query: "Ylvis The Fox", title: "The Fox (What Does the Fox Say?)" },
  { query: "Zayn Pillowtalk", title: "Pillowtalk" }
];
export const ARTISTS_HIPHOP = [
  // --- GIANTS (Catalog Artists) ---
  "2Pac",
  "50 Cent",
  "Aaliyah",
  "Akon",
  "Alicia Keys",
  "Beastie Boys",
  "Beyoncé",
  "Black Eyed Peas",
  "Boyz II Men",
  "Bruno Mars",
  "Busta Rhymes",
  "Cardi B",
  "Chris Brown",
  "Cypress Hill",
  "Destiny's Child",
  "DMX",
  "Doja Cat",
  "Dr. Dre",
  "Drake",
  "Eminem",
  "En Vogue",
  "Fugees, The",
  "Future",
  "Ice Cube",
  "J. Cole",
  "Janet Jackson",
  "Jay-Z",
  "Jennifer Lopez",
  "John Legend",
  "Justin Timberlake",
  "Kanye West",
  "Kendrick Lamar",
  "Khalid",
  "Lauryn Hill",
  "Lil Wayne",
  "Lizzo",
  "Ludacris",
  "Mariah Carey",
  "Mary J. Blige",
  "Megan Thee Stallion",
  "Missy Elliott",
  "Nas",
  "Nelly",
  "Ne-Yo",
  "Nicki Minaj",
  "Notorious B.I.G., The",
  "OutKast",
  "Pharrell Williams",
  "Pitbull",
  "Post Malone",
  "Public Enemy",
  "Rihanna",
  "Run-D.M.C.",
  "Salt-N-Pepa",
  "Sean Paul",
  "Snoop Dogg",
  "The Weeknd",
  "TLC",
  "Travis Scott",
  "Usher",
  "Will Smith",
  "Wu-Tang Clan",
  "XXXTentacion",

  // --- SPECIFIC HITS & ANTHEMS (Objects) ---
  { query: "Aloe Blacc I Need a Dollar", title: "I Need a Dollar" },
  { query: "Amerie 1 Thing", title: "1 Thing" },
  { query: "Arrested Development People Everyday", title: "People Everyday" },
  { query: "Ashanti Foolish", title: "Foolish" },
  { query: "B.o.B Airplanes", title: "Airplanes" },
  { query: "Baauer Harlem Shake", title: "Harlem Shake" },
  { query: "Bell Biv DeVoe Poison", title: "Poison" },
  { query: "Big Pun Still Not a Player", title: "Still Not a Player" },
  { query: "Biz Markie Just a Friend", title: "Just a Friend" },
  { query: "Blackstreet No Diggity", title: "No Diggity" },
  { query: "Blu Cantrell Hit 'Em Up Style", title: "Hit 'Em Up Style (Oops!)" },
  { query: "Bone Thugs-N-Harmony Tha Crossroads", title: "Tha Crossroads" },
  { query: "Brandy & Monica The Boy Is Mine", title: "The Boy Is Mine" },
  { query: "C+C Music Factory Gonna Make You Sweat", title: "Gonna Make You Sweat (Everybody Dance Now)" },
  { query: "Cam'ron Hey Ma", title: "Hey Ma" },
  { query: "Cassie Me & U", title: "Me & U" },
  { query: "CeeLo Green Fuck You", title: "Fuck You" },
  { query: "Chamillionaire Ridin'", title: "Ridin'" },
  { query: "Ciara 1 2 Step", title: "1, 2 Step" },
  { query: "Coolio Gangsta's Paradise", title: "Gangsta's Paradise" },
  { query: "Craig David 7 Days", title: "7 Days" },
  { query: "D12 My Band", title: "My Band" },
  { query: "Da Brat Funkdafied", title: "Funkdafied" },
  { query: "Daddy Yankee Gasolina", title: "Gasolina" },
  { query: "Desiigner Panda", title: "Panda" },
  { query: "Digable Planets Rebirth of Slick", title: "Rebirth of Slick (Cool Like Dat)" },
  { query: "Digital Underground The Humpty Dance", title: "The Humpty Dance" },
  { query: "DJ Jazzy Jeff & The Fresh Prince Summertime", title: "Summertime" },
  { query: "DJ Snake Turn Down for What", title: "Turn Down for What" },
  { query: "Donell Jones U Know What's Up", title: "U Know What's Up" },
  { query: "Estelle American Boy", title: "American Boy" },
  { query: "Eve Let Me Blow Ya Mind", title: "Let Me Blow Ya Mind" },
  { query: "Fat Joe Lean Back", title: "Lean Back" },
  { query: "Fetty Wap Trap Queen", title: "Trap Queen" },
  { query: "Frankie Smith Double Dutch Bus", title: "Double Dutch Bus" },
  { query: "French Montana Unforgettable", title: "Unforgettable" },
  { query: "Game Hate It or Love It", title: "Hate It or Love It" },
  { query: "Ginuwine Pony", title: "Pony" },
  { query: "Gnarls Barkley Crazy", title: "Crazy" },
  { query: "Grandmaster Flash The Message", title: "The Message" },
  { query: "Gym Class Heroes Cupid's Chokehold", title: "Cupid's Chokehold" },
  { query: "House of Pain Jump Around", title: "Jump Around" },
  { query: "Ice-T Colors", title: "Colors" },
  { query: "Iggy Azalea Fancy", title: "Fancy" },
  { query: "Ini Kamoze Here Comes the Hotstepper", title: "Here Comes the Hotstepper" },
  { query: "Ja Rule Always On Time", title: "Always On Time" },
  { query: "Jagged Edge Where the Party At", title: "Where the Party At" },
  { query: "Jeremih Birthday Sex", title: "Birthday Sex" },
  { query: "J-Kwon Tipsy", title: "Tipsy" },
  { query: "Kelis Milkshake", title: "Milkshake" },
  { query: "Kevin Lyttle Turn Me On", title: "Turn Me On" },
  { query: "Kris Kross Jump", title: "Jump" },
  { query: "Lil Jon Get Low", title: "Get Low" },
  { query: "Lil Nas X Old Town Road", title: "Old Town Road" },
  { query: "Logic 1-800-273-8255", title: "1-800-273-8255" },
  { query: "Luniz I Got 5 On It", title: "I Got 5 On It" },
  { query: "M.I.A. Paper Planes", title: "Paper Planes" },
  { query: "Macklemore Thrift Shop", title: "Thrift Shop" },
  { query: "Mario Let Me Love You", title: "Let Me Love You" },
  { query: "Mark Morrison Return of the Mack", title: "Return of the Mack" },
  { query: "Mase Feel So Good", title: "Feel So Good" },
  { query: "Montell Jordan This Is How We Do It", title: "This Is How We Do It" },
  { query: "N.E.R.D She Wants to Move", title: "She Wants to Move" },
  { query: "Naughty By Nature Hip Hop Hooray", title: "Hip Hop Hooray" },
  { query: "Nelly Furtado Promiscuous", title: "Promiscuous" },
  { query: "Next Too Close", title: "Too Close" },
  { query: "Ol' Dirty Bastard Shimmy Shimmy Ya", title: "Shimmy Shimmy Ya" },
  { query: "Panjabi MC Mundian To Bach Ke", title: "Mundian To Bach Ke" },
  { query: "Pras Ghetto Supastar", title: "Ghetto Supastar" },
  { query: "Rae Sremmurd Black Beatles", title: "Black Beatles" },
  { query: "Rick Ross Hustlin'", title: "Hustlin'" },
  { query: "Robin Thicke Blurred Lines", title: "Blurred Lines" },
  { query: "Shaggy It Wasn't Me", title: "It Wasn't Me" },
  { query: "Shania Twain That Don't Impress Me Much", title: "That Don't Impress Me Much" },
  { query: "Sisqo Thong Song", title: "Thong Song" },
  { query: "Silentó Watch Me", title: "Watch Me (Whip/Nae Nae)" },
  { query: "Sir Mix-A-Lot Baby Got Back", title: "Baby Got Back" },
  { query: "Soulja Boy Crank That", title: "Crank That (Soulja Boy)" },
  { query: "St. Lunatics Shake Ya Tailfeather", title: "Shake Ya Tailfeather" },
  { query: "Sugarhill Gang Rapper's Delight", title: "Rapper's Delight" },
  { query: "Tag Team Whoomp There It Is", title: "Whoomp! (There It Is)" },
  { query: "Terror Squad Lean Back", title: "Lean Back" },
  { query: "Tinie Tempah Written in the Stars", title: "Written in the Stars" },
  { query: "Tone Lōc Funky Cold Medina", title: "Funky Cold Medina" },
  { query: "T-Pain Buy U a Drank", title: "Buy U a Drank" },
  { query: "Trey Songz Bottoms Up", title: "Bottoms Up" },
  { query: "Truth Hurts Addictive", title: "Addictive" },
  { query: "Tweet Oops Oh My", title: "Oops (Oh My)" },
  { query: "Twista Slow Jamz", title: "Slow Jamz" },
  { query: "Tyga Rack City", title: "Rack City" },
  { query: "Vanilla Ice Ice Ice Baby", title: "Ice Ice Baby" },
  { query: "Wale Lotus Flower Bomb", title: "Lotus Flower Bomb" },
  { query: "Warren G Regulate", title: "Regulate" },
  { query: "Wiz Khalifa Black and Yellow", title: "Black and Yellow" },
  { query: "Wyclef Jean Gone Till November", title: "Gone Till November" },
  { query: "Xzibit X", title: "X" },
  { query: "Young MC Bust A Move", title: "Bust A Move" }
];
export const MOVIE_THEMES = [
  // --- MOVIES: Sci-Fi, Fantasy & Superhero ---
  { query: "John Williams Star Wars Main Title", title: "Star Wars" },
  { query: "John Williams The Imperial March", title: "Star Wars (The Empire Strikes Back)" },
  { query: "John Williams Duel of the Fates", title: "Star Wars (The Phantom Menace)" },
  { query: "Howard Shore The Fellowship of the Ring", title: "The Lord of the Rings" },
  { query: "John Williams Hedwig's Theme", title: "Harry Potter" },
  { query: "John Williams Jurassic Park Theme", title: "Jurassic Park" },
  { query: "Alan Silvestri Back to the Future Theme", title: "Back to the Future" },
  { query: "Richard Strauss Also sprach Zarathustra", title: "2001: A Space Odyssey" },
  { query: "John Williams E.T. Flying Theme", title: "E.T. the Extra-Terrestrial" },
  { query: "Brad Fiedel The Terminator Theme", title: "The Terminator" },
  { query: "Vangelis Blade Runner End Titles", title: "Blade Runner" },
  { query: "Hans Zimmer Time Inception", title: "Inception" },
  { query: "Hans Zimmer Cornfield Chase", title: "Interstellar" },
  { query: "Jerry Goldsmith Star Trek Main Title", title: "Star Trek: The Motion Picture" },
  { query: "Danny Elfman Batman Theme", title: "Batman (1989)" },
  { query: "Hans Zimmer The Dark Knight Theme", title: "The Dark Knight" },
  { query: "John Williams Superman Main Title", title: "Superman" },
  { query: "Alan Silvestri The Avengers Theme", title: "The Avengers" },
  { query: "Danny Elfman Spider-Man Main Title", title: "Spider-Man (Raimi)" },
  { query: "Ludwig Göransson Wakanda", title: "Black Panther" },
  { query: "Wendy Carlos Tron Theme", title: "Tron" },
  { query: "Daft Punk Tron Legacy End Titles", title: "Tron: Legacy" },

  // --- MOVIES: Action & Adventure ---
  { query: "John Williams Raiders March", title: "Indiana Jones" },
  { query: "Monty Norman James Bond Theme", title: "James Bond 007" },
  { query: "Adele Skyfall", title: "Skyfall (James Bond)" },
  { query: "Lalo Schifrin Mission Impossible", title: "Mission: Impossible" },
  { query: "Klaus Badelt He's a Pirate", title: "Pirates of the Caribbean" },
  { query: "Hans Zimmer Gladiator Now We Are Free", title: "Gladiator" },
  { query: "Ennio Morricone The Good, the Bad and the Ugly", title: "The Good, the Bad and the Ugly" },
  { query: "Ennio Morricone Ecstasy of Gold", title: "The Good, the Bad and the Ugly (Ecstasy)" },
  { query: "Elmer Bernstein The Magnificent Seven", title: "The Magnificent Seven" },
  { query: "Elmer Bernstein The Great Escape March", title: "The Great Escape" },
  { query: "Harold Faltermeyer Top Gun Anthem", title: "Top Gun" },
  { query: "Kenny Loggins Danger Zone", title: "Top Gun (Danger Zone)" },
  { query: "Harold Faltermeyer Axel F", title: "Beverly Hills Cop" },
  { query: "Bill Conti Gonna Fly Now", title: "Rocky" },
  { query: "Survivor Eye of the Tiger", title: "Rocky III" },
  { query: "Vangelis Chariots of Fire", title: "Chariots of Fire" },
  { query: "Basil Poledouris Conan the Barbarian Theme", title: "Conan the Barbarian" },

  // --- MOVIES: Drama, Romance, Comedy & Cult ---
  { query: "Nino Rota The Godfather Waltz", title: "The Godfather" },
  { query: "Celine Dion My Heart Will Go On", title: "Titanic" },
  { query: "James Horner Braveheart Theme", title: "Braveheart" },
  { query: "Alan Silvestri Forrest Gump Suite", title: "Forrest Gump" },
  { query: "John Williams Schindler's List Theme", title: "Schindler's List" },
  { query: "Ennio Morricone Cinema Paradiso", title: "Cinema Paradiso" },
  { query: "Yann Tiersen Comptine d'un autre été", title: "Amélie" },
  { query: "Francis Lai Love Story", title: "Love Story" },
  { query: "Maurice Jarre Lara's Theme", title: "Doctor Zhivago" },
  { query: "Henry Mancini Moon River", title: "Breakfast at Tiffany's" },
  { query: "Whitney Houston I Will Always Love You", title: "The Bodyguard" },
  { query: "Bill Medley (I've Had) The Time of My Life", title: "Dirty Dancing" },
  { query: "Ray Parker Jr. Ghostbusters", title: "Ghostbusters" },
  { query: "Dick Dale Misirlou", title: "Pulp Fiction" },
  { query: "Chuck Berry You Never Can Tell", title: "Pulp Fiction (Twist)" },
  { query: "Simon & Garfunkel Mrs. Robinson", title: "The Graduate" },
  { query: "Huey Lewis The Power of Love", title: "Back to the Future (Song)" },
  { query: "Simple Minds Don't You Forget About Me", title: "The Breakfast Club" },
  { query: "Berlin Take My Breath Away", title: "Top Gun (Love Theme)" },
  { query: "Urge Overkill Girl, You'll Be a Woman Soon", title: "Pulp Fiction" },
  { query: "Steppenwolf Born to Be Wild", title: "Easy Rider" },
  { query: "Isaac Hayes Theme from Shaft", title: "Shaft" },
  { query: "Curtis Mayfield Superfly", title: "Superfly" },
  { query: "Bee Gees Stayin' Alive", title: "Saturday Night Fever" },
  { query: "John Travolta You're the One That I Want", title: "Grease" },
  { query: "Irene Cara Flashdance What a Feeling", title: "Flashdance" },
  { query: "Kenny Loggins Footloose", title: "Footloose" },
  { query: "Dolly Parton 9 to 5", title: "9 to 5" },
  { query: "Roy Orbison Pretty Woman", title: "Pretty Woman" },
  { query: "Righteous Brothers Unchained Melody", title: "Ghost" },
  { query: "Aerosmith I Don't Want to Miss a Thing", title: "Armageddon" },
  { query: "Coolio Gangsta's Paradise", title: "Dangerous Minds" },
  { query: "Eminem Lose Yourself", title: "8 Mile" },
  { query: "Pixies Where Is My Mind", title: "Fight Club" },
  
  // --- MOVIES: Horror & Thriller ---
  { query: "John Williams Jaws Theme", title: "Jaws" },
  { query: "John Carpenter Halloween Theme", title: "Halloween" },
  { query: "Bernard Herrmann Psycho Prelude", title: "Psycho" },
  { query: "Mike Oldfield Tubular Bells", title: "The Exorcist" },
  { query: "Goblin Suspiria", title: "Suspiria" },
  { query: "Charlie Clouser Hello Zepp", title: "Saw" },
  { query: "Danny Elfman Tales from the Crypt", title: "Tales from the Crypt" },

  // --- MOVIES: Animation & Disney ---
  { query: "Elton John Circle of Life", title: "The Lion King" },
  { query: "Brad Kane A Whole New World", title: "Aladdin" },
  { query: "Samuel E. Wright Under the Sea", title: "The Little Mermaid" },
  { query: "Idina Menzel Let It Go", title: "Frozen" },
  { query: "Randy Newman You've Got a Friend in Me", title: "Toy Story" },
  { query: "Danny Elfman This Is Halloween", title: "The Nightmare Before Christmas" },
  { query: "Ray Charles Shake a Tail Feather", title: "The Blues Brothers" },
  { query: "Pharrell Williams Happy", title: "Despicable Me 2" },
  { query: "Smash Mouth All Star", title: "Shrek" },

  // --- TV: Classic Era (50s, 60s, 70s) ---
  { query: "Marius Constant The Twilight Zone Theme", title: "The Twilight Zone" },
  { query: "Alexander Courage Star Trek Original Series Theme", title: "Star Trek (TOS)" },
  { query: "Neal Hefti Batman Theme", title: "Batman (1966 Series)" },
  { query: "Vic Mizzy The Addams Family Theme", title: "The Addams Family" },
  { query: "Hoyt Curtin The Flintstones Theme", title: "The Flintstones" },
  { query: "Lalo Schifrin Mission Impossible TV Theme", title: "Mission: Impossible (TV)" },
  { query: "Henry Mancini The Pink Panther Theme", title: "The Pink Panther" },
  { query: "Morton Stevens Hawaii Five-O Theme", title: "Hawaii Five-O" },
  { query: "Johnny Mandel Suicide Is Painless", title: "M*A*S*H" },
  { query: "Jerrold Immel Dallas Theme", title: "Dallas" },
  { query: "Pratt & McClain Happy Days", title: "Happy Days" },
  { query: "Jim Henson The Muppet Show Theme", title: "The Muppet Show" },
  { query: "Charles Gounod Funeral March of a Marionette", title: "Alfred Hitchcock Presents" },
  { query: "Jay Livingston Bonanza Theme", title: "Bonanza" },
  { query: "Theme from The Jeffersons Movin' On Up", title: "The Jeffersons" },
  { query: "Theme from Sanford and Son The Streetbeater", title: "Sanford and Son" },
  { query: "Andrew Gold Thank You for Being a Friend", title: "The Golden Girls" },

  // --- TV: The 80s Action, Cult & Sitcoms ---
  { query: "Jan Hammer Miami Vice Theme", title: "Miami Vice" },
  { query: "Mike Post The A-Team Theme", title: "The A-Team" },
  { query: "Stu Phillips Knight Rider Theme", title: "Knight Rider" },
  { query: "Randy Edelman MacGyver Theme", title: "MacGyver" },
  { query: "Mike Post Magnum P.I. Theme", title: "Magnum, P.I." },
  { query: "Sylvester Levay Airwolf Theme", title: "Airwolf" },
  { query: "Waylon Jennings Good Ol' Boys", title: "The Dukes of Hazzard" },
  { query: "Jimi Jamison I'm Always Here", title: "Baywatch" },
  { query: "Gary Portnoy Where Everybody Knows Your Name", title: "Cheers" },
  { query: "Judy Hart Angelo The Theme from Hill Street Blues", title: "Hill Street Blues" },
  { query: "Joey Scarbury Believe It or Not", title: "The Greatest American Hero" },
  { query: "Bill Cosby The Cosby Show Theme", title: "The Cosby Show" },

  // --- TV: The 90s Classics ---
  { query: "Rembrandts I'll Be There For You", title: "Friends" },
  { query: "Jonathan Wolff Seinfeld Theme", title: "Seinfeld" },
  { query: "Will Smith The Fresh Prince of Bel-Air", title: "The Fresh Prince of Bel-Air" },
  { query: "Danny Elfman The Simpsons Theme", title: "The Simpsons" },
  { query: "Frank Sinatra Love and Marriage", title: "Married... with Children" },
  { query: "Mark Snow The X-Files Theme", title: "The X-Files" },
  { query: "Angelo Badalamenti Twin Peaks Theme", title: "Twin Peaks" },
  { query: "Nerf Herder Buffy the Vampire Slayer Theme", title: "Buffy the Vampire Slayer" },
  { query: "Groove Armada Sex and the City Theme", title: "Sex and the City" },
  { query: "Paula Cole I Don't Want to Wait", title: "Dawson's Creek" },
  { query: "Bad Circle Bad Boys", title: "Cops" },
  { query: "TLC Creep", title: "TLC" }, 
  { query: "Kelsey Grammer Tossed Salad and Scrambled Eggs", title: "Frasier" },
  { query: "Jesse Frederick Everywhere You Look", title: "Full House" },
  { query: "Scott Grimes Sunset Beach", title: "Sunset Beach" },
  { query: "Vonda Shepard Searchin' My Soul", title: "Ally McBeal" },

  // --- TV: 2000s - 2020s Prestige & Hits ---
  { query: "Ramin Djawadi Game of Thrones Main Title", title: "Game of Thrones" },
  { query: "Alabama 3 Woke Up This Morning", title: "The Sopranos" },
  { query: "Kyle Dixon & Michael Stein Stranger Things", title: "Stranger Things" },
  { query: "Bear McCreary The Walking Dead Theme", title: "The Walking Dead" },
  { query: "Nicholas Britell Succession Main Title", title: "Succession" },
  { query: "John Lunn Downton Abbey Theme", title: "Downton Abbey" },
  { query: "RJD2 A Beautiful Mine", title: "Mad Men" },
  { query: "Massive Attack Teardrop", title: "House M.D." },
  { query: "Ludwig Göransson The Mandalorian", title: "The Mandalorian" },
  { query: "The Who Won't Get Fooled Again", title: "CSI: Miami" },
  { query: "The Who Who Are You", title: "CSI: Crime Scene Investigation" },
  { query: "Wazmo Nariz Narcos Theme Tuyo", title: "Narcos" },
  { query: "Cecilia Krull My Life Is Going On", title: "Money Heist (La Casa de Papel)" },
  { query: "Marcus Mumford Ted Lasso Theme", title: "Ted Lasso" },
  { query: "Cristobal Tapia de Veer Renaissance", title: "The White Lotus" },
  { query: "Hans Zimmer The Crown Main Title", title: "The Crown" },
  { query: "Jeff Beal House of Cards Theme", title: "House of Cards" },
  { query: "Murray Gold Doctor Who Theme", title: "Doctor Who" },
  { query: "David Arnold Sherlock Theme", title: "Sherlock" },
  { query: "Thomas Newman Angels in America", title: "Angels in America" },
  { query: "Regina Spektor You've Got Time", title: "Orange Is the New Black" },
  { query: "The Rembrandts I'll Be There For You", title: "Friends" },
  { query: "Phantom Planet California", title: "The O.C." },
  { query: "Gavin DeGraw I Don't Want to Be", title: "One Tree Hill" },
  { query: "Lazlo Bane Superman", title: "Scrubs" },
  { query: "Barenaked Ladies The Big Bang Theory Theme", title: "The Big Bang Theory" },
  { query: "The Solids Hey Beautiful", title: "How I Met Your Mother" },
  { query: "The 88 At Least It Was Here", title: "Community" },
  { query: "Zooey Deschanel Hey Girl", title: "New Girl" },
  { query: "Nick Cave Red Right Hand", title: "Peaky Blinders" },
  { query: "The Handsome Family Far From Any Road", title: "True Detective" },
  { query: "Apparat Goodbye", title: "Dark" },
  { query: "Sonny Rhodes The Ballad of Serenity", title: "Firefly" },
  { query: "Dave Porter Breaking Bad Theme", title: "Breaking Bad" },
  { query: "Shaggy It Wasn't Me", title: "The Shaggy Show" }, // (Humorous placeholder, verify context)
  { query: "Michael Kiwanuka Cold Little Heart", title: "Big Little Lies" },

  // --- CARTOONS & ANIME ---
  { query: "Jason Paige Pokémon Theme", title: "Pokémon" },
  { query: "Hironobu Kageyama Cha-La Head-Cha", title: "Dragon Ball Z" },
  { query: "Hiroshi Kitadani We Are", title: "One Piece" },
  { query: "Yoko Takahashi A Cruel Angel's Thesis", title: "Neon Genesis Evangelion" },
  { query: "The Seatbelts Tank!", title: "Cowboy Bebop" },
  { query: "Mark Mueller DuckTales Theme", title: "DuckTales" },
  { query: "Chuck Lorre Teenage Mutant Ninja Turtles Theme", title: "Teenage Mutant Ninja Turtles" },
  { query: "Ron Wasserman Go Go Power Rangers", title: "Mighty Morphin Power Rangers" },
  { query: "Ron Wasserman X-Men Animated Series Theme", title: "X-Men (Animated)" },
  { query: "Danny Elfman Batman The Animated Series", title: "Batman: The Animated Series" },
  { query: "Family Guy Theme Song", title: "Family Guy" },
  { query: "Trey Parker South Park Theme", title: "South Park" },
  { query: "SpongeBob SquarePants Theme Song", title: "SpongeBob SquarePants" },
  { query: "Lin-Manuel Miranda We Don't Talk About Bruno", title: "Encanto" }
];
export const FOOTBALL_CAREERS = [
  // --- LEVEL 1: THE SUPERSTARS (Very Easy) ---
  {
    player: "Kylian Mbappé",
    difficulty: 1,
    clubs: ["Monaco", "Paris Saint Germain", "Real Madrid"]
  },
  {
    player: "Erling Haaland",
    difficulty: 1,
    clubs: ["Molde", "Red Bull Salzburg", "Borussia Dortmund", "Manchester City"]
  },
  {
    player: "Karim Benzema",
    difficulty: 1,
    clubs: ["Lyon", "Real Madrid", "Al-Ittihad"]
  },
  {
    player: "Kaka",
    difficulty: 1,
    clubs: ["Sao Paulo", "AC Milan", "Real Madrid", "AC Milan", "Orlando City"]
  },
  {
    player: "Gianluigi Buffon",
    difficulty: 1,
    clubs: ["Parma", "Juventus", "Paris Saint Germain", "Juventus", "Parma"]
  },
  {
    player: "Luka Modrić",
    difficulty: 1,
    clubs: ["Dinamo Zagreb", "Tottenham Hotspur", "Real Madrid"]
  },
  {
    player: "Manuel Neuer",
    difficulty: 1,
    clubs: ["Schalke 04", "Bayern Munich"]
  },
  {
    player: "Frank Lampard",
    difficulty: 1,
    clubs: ["West Ham United", "Chelsea", "Manchester City", "New York City FC"]
  },
  {
    player: "Steven Gerrard",
    difficulty: 1,
    clubs: ["Liverpool", "LA Galaxy"]
  },
  {
    player: "Sergio Agüero",
    difficulty: 1,
    clubs: ["Independiente", "Atletico Madrid", "Manchester City", "Barcelona"]
  },
  {
    player: "Zlatan Ibrahimović",
    difficulty: 1,
    clubs: ["Malmo FF", "Ajax", "Juventus", "Inter Milan", "Barcelona", "AC Milan", "Paris Saint Germain", "Manchester United", "LA Galaxy", "AC Milan"]
  },
  {
    player: "Cristiano Ronaldo",
    difficulty: 1,
    clubs: ["Sporting CP", "Manchester United", "Real Madrid", "Juventus", "Manchester United", "Al Nassr"]
  },
  {
    player: "Lionel Messi",
    difficulty: 1,
    clubs: ["Barcelona", "Paris Saint Germain", "Inter Miami"]
  },
  {
    player: "Neymar",
    difficulty: 1,
    clubs: ["Santos", "Barcelona", "Paris Saint Germain", "Al Hilal"]
  },
  {
    player: "David Beckham",
    difficulty: 1,
    clubs: ["Manchester United", "Preston North End", "Real Madrid", "LA Galaxy", "AC Milan", "Paris Saint Germain"]
  },
  {
    player: "Thierry Henry",
    difficulty: 1,
    clubs: ["Monaco", "Juventus", "Arsenal", "Barcelona", "New York Red Bulls"]
  },
  {
    player: "Wayne Rooney",
    difficulty: 1,
    clubs: ["Everton", "Manchester United", "Everton", "DC United", "Derby County"]
  },
  {
    player: "Ronaldinho",
    difficulty: 1,
    clubs: ["Gremio", "Paris Saint Germain", "Barcelona", "AC Milan", "Flamengo", "Atletico Mineiro", "Queretaro", "Fluminense"]
  },
  {
    player: "Ronaldo Nazário",
    difficulty: 1,
    clubs: ["Cruzeiro", "PSV Eindhoven", "Barcelona", "Inter Milan", "Real Madrid", "AC Milan", "Corinthians"]
  },

  // --- LEVEL 2: LEGENDS & STARS (Easy) ---
  {
    player: "Patrick Vieira",
    difficulty: 2,
    clubs: ["Cannes", "AC Milan", "Arsenal", "Juventus", "Inter Milan", "Manchester City"]
  },
  {
    player: "Petr Čech",
    difficulty: 2,
    clubs: ["Rennes", "Chelsea", "Arsenal"]
  },
  {
    player: "Rio Ferdinand",
    difficulty: 2,
    clubs: ["West Ham United", "Leeds United", "Manchester United", "Queens Park Rangers"]
  },
  {
    player: "Iker Casillas",
    difficulty: 2,
    clubs: ["Real Madrid", "Porto"]
  },
  {
    player: "Dani Alves",
    difficulty: 2,
    clubs: ["Sevilla", "Barcelona", "Juventus", "Paris Saint Germain", "Sao Paulo", "Pumas UNAM"]
  },
  {
    player: "Ruud van Nistelrooy",
    difficulty: 2,
    clubs: ["PSV Eindhoven", "Manchester United", "Real Madrid", "Hamburg", "Malaga"]
  },
  {
    player: "Fabio Cannavaro",
    difficulty: 2,
    clubs: ["Parma", "Inter Milan", "Juventus", "Real Madrid", "Juventus", "Al Ahli"]
  },
  {
    player: "Roberto Carlos",
    difficulty: 2,
    clubs: ["Inter Milan", "Real Madrid", "Fenerbahce", "Corinthians", "Anzhi Makhachkala"]
  },
  {
    player: "Rivaldo",
    difficulty: 2,
    clubs: ["Deportivo La Coruna", "Barcelona", "AC Milan", "Olympiacos", "AEK Athens"]
  },
  {
    player: "Cafu",
    difficulty: 2,
    clubs: ["Real Zaragoza", "Palmeiras", "Roma", "AC Milan"]
  },
  {
    player: "Gareth Bale",
    difficulty: 2,
    clubs: ["Southampton", "Tottenham Hotspur", "Real Madrid", "Tottenham Hotspur", "Los Angeles FC"]
  },
  {
    player: "Luis Suárez",
    difficulty: 2,
    clubs: ["Nacional", "Groningen", "Ajax", "Liverpool", "Barcelona", "Atletico Madrid", "Gremio", "Inter Miami"]
  },
  {
    player: "Robert Lewandowski",
    difficulty: 2,
    clubs: ["Lech Poznan", "Borussia Dortmund", "Bayern Munich", "Barcelona"]
  },
  {
    player: "Eden Hazard",
    difficulty: 2,
    clubs: ["Lille", "Chelsea", "Real Madrid"]
  },
  {
    player: "Sergio Ramos",
    difficulty: 2,
    clubs: ["Sevilla", "Real Madrid", "Paris Saint Germain", "Sevilla"]
  },
  {
    player: "Zinedine Zidane",
    difficulty: 2,
    clubs: ["Cannes", "Bordeaux", "Juventus", "Real Madrid"]
  },
  {
    player: "Andrea Pirlo",
    difficulty: 2,
    clubs: ["Brescia", "Inter Milan", "AC Milan", "Juventus", "New York City FC"]
  },
  {
    player: "Luís Figo",
    difficulty: 2,
    clubs: ["Sporting CP", "Barcelona", "Real Madrid", "Inter Milan"]
  },
  {
    player: "Xabi Alonso",
    difficulty: 2,
    clubs: ["Real Sociedad", "Eibar", "Liverpool", "Real Madrid", "Bayern Munich"]
  },
  {
    player: "Cesc Fàbregas",
    difficulty: 2,
    clubs: ["Arsenal", "Barcelona", "Chelsea", "Monaco", "Como"]
  },

  // --- LEVEL 3: THE 2000-2015 ICONS (Medium) ---
  {
    player: "Henrik Larsson",
    difficulty: 3,
    clubs: ["Feyenoord", "Celtic", "Barcelona", "Helsingborgs IF", "Manchester United"]
  },
  {
    player: "Michael Ballack",
    difficulty: 3,
    clubs: ["Kaiserslautern", "Bayer Leverkusen", "Bayern Munich", "Chelsea", "Bayer Leverkusen"]
  },
  {
    player: "Clarence Seedorf",
    difficulty: 3,
    clubs: ["Ajax", "Sampdoria", "Real Madrid", "Inter Milan", "AC Milan", "Botafogo"]
  },
  {
    player: "Edwin van der Sar",
    difficulty: 3,
    clubs: ["Ajax", "Juventus", "Fulham", "Manchester United"]
  },
  {
    player: "Patrick Kluivert",
    difficulty: 3,
    clubs: ["Ajax", "AC Milan", "Barcelona", "Newcastle United", "Valencia", "PSV Eindhoven", "Lille"]
  },
  {
    player: "Sol Campbell",
    difficulty: 3,
    clubs: ["Tottenham Hotspur", "Arsenal", "Portsmouth", "Notts County", "Newcastle United"]
  },
  {
    player: "Robert Pires",
    difficulty: 3,
    clubs: ["Metz", "Marseille", "Arsenal", "Villarreal", "Aston Villa", "Goa"]
  },
  {
    player: "Vincent Kompany",
    difficulty: 3,
    clubs: ["Anderlecht", "Hamburg", "Manchester City", "Anderlecht"]
  },
  {
    player: "David Silva",
    difficulty: 3,
    clubs: ["Valencia", "Manchester City", "Real Sociedad"]
  },
  {
    player: "Nemanja Vidic",
    difficulty: 3,
    clubs: ["Spartak Moscow", "Manchester United", "Inter Milan"]
  },
  {
    player: "Arjen Robben",
    difficulty: 3,
    clubs: ["Groningen", "PSV Eindhoven", "Chelsea", "Real Madrid", "Bayern Munich"]
  },
  {
    player: "Samuel Eto'o",
    difficulty: 3,
    clubs: ["Real Madrid", "Mallorca", "Barcelona", "Inter Milan", "Anzhi Makhachkala", "Chelsea", "Everton", "Sampdoria"]
  },
  {
    player: "Carlos Tevez",
    difficulty: 3,
    clubs: ["Boca Juniors", "Corinthians", "West Ham United", "Manchester United", "Manchester City", "Juventus", "Boca Juniors", "Shanghai Shenhua"]
  },
  {
    player: "Fernando Torres",
    difficulty: 3,
    clubs: ["Atletico Madrid", "Liverpool", "Chelsea", "AC Milan", "Atletico Madrid", "Sagan Tosu"]
  },
  {
    player: "Robin van Persie",
    difficulty: 3,
    clubs: ["Feyenoord", "Arsenal", "Manchester United", "Fenerbahce"]
  },
  {
    player: "Michael Owen",
    difficulty: 3,
    clubs: ["Liverpool", "Real Madrid", "Newcastle United", "Manchester United", "Stoke City"]
  },
  {
    player: "Bastian Schweinsteiger",
    difficulty: 3,
    clubs: ["Bayern Munich", "Manchester United", "Chicago Fire"]
  },
  {
    player: "Didier Drogba",
    difficulty: 3,
    clubs: ["Guingamp", "Marseille", "Chelsea", "Shanghai Shenhua", "Galatasaray", "Montreal Impact"]
  },
  {
    player: "Yaya Touré",
    difficulty: 3,
    clubs: ["Beveren", "Metalurh Donetsk", "Olympiacos", "Monaco", "Barcelona", "Manchester City"]
  },
  {
    player: "Gerard Piqué",
    difficulty: 3,
    clubs: ["Manchester United", "Real Zaragoza", "Barcelona"]
  },
  {
    player: "Wesley Sneijder",
    difficulty: 3,
    clubs: ["Ajax", "Real Madrid", "Inter Milan", "Galatasaray", "Nice", "Al-Gharafa"]
  },
  {
    player: "Miroslav Klose",
    difficulty: 3,
    clubs: ["Kaiserslautern", "Werder Bremen", "Bayern Munich", "Lazio"]
  },
  {
    player: "Claude Makélélé",
    difficulty: 3,
    clubs: ["Nantes", "Marseille", "Celta Vigo", "Real Madrid", "Chelsea", "Paris Saint Germain"]
  },

  // --- LEVEL 4: CULT HEROES & TRAVELERS (Hard) ---
  {
    player: "Eidur Gudjohnsen",
    difficulty: 4,
    clubs: ["Bolton", "Chelsea", "Barcelona", "Monaco", "Tottenham Hotspur", "Stoke City", "Fulham", "AEK Athens", "Club Brugge", "Molde"]
  },
  {
    player: "Jermain Defoe",
    difficulty: 4,
    clubs: ["West Ham United", "Tottenham Hotspur", "Portsmouth", "Tottenham Hotspur", "Toronto FC", "Sunderland", "Bournemouth", "Rangers"]
  },
  {
    player: "Alexis Sánchez",
    difficulty: 4,
    clubs: ["Udinese", "Barcelona", "Arsenal", "Manchester United", "Inter Milan", "Marseille", "Inter Milan", "Udinese"]
  },
  {
    player: "Mesut Özil",
    difficulty: 4,
    clubs: ["Schalke 04", "Werder Bremen", "Real Madrid", "Arsenal", "Fenerbahce", "Istanbul Basaksehir"]
  },
  {
    player: "Pierre-Emerick Aubameyang",
    difficulty: 4,
    clubs: ["AC Milan", "Saint-Etienne", "Borussia Dortmund", "Arsenal", "Barcelona", "Chelsea", "Marseille", "Al Qadsiah"]
  },
  {
    player: "Radamel Falcao",
    difficulty: 4,
    clubs: ["River Plate", "Porto", "Atletico Madrid", "Monaco", "Manchester United", "Chelsea", "Galatasaray", "Rayo Vallecano", "Millonarios"]
  },
  {
    player: "Gonzalo Higuaín",
    difficulty: 4,
    clubs: ["River Plate", "Real Madrid", "Napoli", "Juventus", "AC Milan", "Chelsea", "Inter Miami"]
  },
  {
    player: "Philippe Coutinho",
    difficulty: 4,
    clubs: ["Inter Milan", "Espanyol", "Liverpool", "Barcelona", "Bayern Munich", "Aston Villa", "Al-Duhail", "Vasco da Gama"]
  },
  {
    player: "Antonio Cassano",
    difficulty: 4,
    clubs: ["Bari", "Roma", "Real Madrid", "Sampdoria", "AC Milan", "Inter Milan", "Parma", "Sampdoria"]
  },
  {
    player: "Robbie Fowler",
    difficulty: 4,
    clubs: ["Liverpool", "Leeds United", "Manchester City", "Liverpool", "Cardiff City", "Blackburn Rovers", "North Queensland Fury", "Perth Glory"]
  },
  {
    player: "Nicolas Anelka",
    difficulty: 4,
    clubs: ["Paris Saint Germain", "Arsenal", "Real Madrid", "Liverpool", "Manchester City", "Fenerbahce", "Bolton", "Chelsea", "Shanghai Shenhua", "Juventus", "West Bromwich"]
  },
  {
    player: "Hernán Crespo",
    difficulty: 4,
    clubs: ["River Plate", "Parma", "Lazio", "Inter Milan", "Chelsea", "AC Milan", "Genoa", "Parma"]
  },
  {
    player: "Edgar Davids",
    difficulty: 4,
    clubs: ["Ajax", "AC Milan", "Juventus", "Barcelona", "Inter Milan", "Tottenham Hotspur", "Crystal Palace", "Barnet"]
  },
  {
    player: "Deco",
    difficulty: 4,
    clubs: ["Corinthians", "Alverca", "Salgueiros", "Porto", "Barcelona", "Chelsea", "Fluminense"]
  },
  {
    player: "Dimitar Berbatov",
    difficulty: 4,
    clubs: ["CSKA Sofia", "Bayer Leverkusen", "Tottenham Hotspur", "Manchester United", "Fulham", "Monaco", "PAOK"]
  },
  {
    player: "Juan Mata",
    difficulty: 4,
    clubs: ["Real Madrid Castilla", "Valencia", "Chelsea", "Manchester United", "Galatasaray", "Vissel Kobe"]
  },
  {
    player: "Diego Forlán",
    difficulty: 4,
    clubs: ["Independiente", "Manchester United", "Villarreal", "Atletico Madrid", "Inter Milan", "Internacional", "Cerezo Osaka", "Penarol"]
  },
  {
    player: "Patrice Evra",
    difficulty: 4,
    clubs: ["Marsala", "Monza", "Nice", "Monaco", "Manchester United", "Juventus", "Marseille", "West Ham United"]
  },
  {
    player: "Rafael van der Vaart",
    difficulty: 4,
    clubs: ["Ajax", "Hamburg", "Real Madrid", "Tottenham Hotspur", "Hamburg", "Real Betis", "Midtjylland"]
  },
  {
    player: "Javier Mascherano",
    difficulty: 4,
    clubs: ["River Plate", "Corinthians", "West Ham United", "Liverpool", "Barcelona", "Hebei China Fortune", "Estudiantes"]
  },
  {
    player: "Mario Balotelli",
    difficulty: 4,
    clubs: ["Inter Milan", "Manchester City", "AC Milan", "Liverpool", "Nice", "Marseille", "Brescia", "Monza", "Adana Demirspor", "Sion"]
  },
  {
    player: "James Rodríguez",
    difficulty: 4,
    clubs: ["Envigado", "Banfield", "Porto", "Monaco", "Real Madrid", "Bayern Munich", "Everton", "Al-Rayyan", "Olympiacos", "Sao Paulo", "Rayo Vallecano"]
  },
  {
    player: "Ashley Cole",
    difficulty: 4,
    clubs: ["Arsenal", "Crystal Palace", "Chelsea", "Roma", "LA Galaxy", "Derby County"]
  },
  {
    player: "Angel Di Maria",
    difficulty: 4,
    clubs: ["Rosario Central", "Benfica", "Real Madrid", "Manchester United", "Paris Saint Germain", "Juventus", "Benfica"]
  },

  // --- LEVEL 5: THE JOURNEYMEN & TRICKY ONES (Expert) ---
  {
    player: "Javier Saviola",
    difficulty: 5,
    clubs: ["River Plate", "Barcelona", "Monaco", "Sevilla", "Real Madrid", "Benfica", "Malaga", "Olympiacos", "Verona", "River Plate"]
  },
  {
    player: "William Gallas",
    difficulty: 5,
    clubs: ["Caen", "Marseille", "Chelsea", "Arsenal", "Tottenham Hotspur", "Perth Glory"]
  },
  {
    player: "John Carew",
    difficulty: 5,
    clubs: ["Valerenga", "Rosenborg", "Valencia", "Roma", "Besiktas", "Lyon", "Aston Villa", "Stoke City", "West Ham United"]
  },
  {
    player: "Obafemi Martins",
    difficulty: 5,
    clubs: ["Inter Milan", "Newcastle United", "Wolfsburg", "Rubin Kazan", "Birmingham City", "Levante", "Seattle Sounders", "Shanghai Shenhua"]
  },
  {
    player: "Maicon",
    difficulty: 5,
    clubs: ["Cruzeiro", "Monaco", "Inter Milan", "Manchester City", "Roma", "Avai", "Criciuma"]
  },
  {
    player: "Lúcio",
    difficulty: 5,
    clubs: ["Internacional", "Bayer Leverkusen", "Bayern Munich", "Inter Milan", "Juventus", "Sao Paulo", "Palmeiras"]
  },
  {
    player: "Diego Ribas",
    difficulty: 5,
    clubs: ["Santos", "Porto", "Werder Bremen", "Juventus", "Wolfsburg", "Atletico Madrid", "Fenerbahce", "Flamengo"]
  },
  {
    player: "Simão Sabrosa",
    difficulty: 5,
    clubs: ["Sporting CP", "Barcelona", "Benfica", "Atletico Madrid", "Besiktas", "Espanyol"]
  },
  {
    player: "Rafael Márquez",
    difficulty: 5,
    clubs: ["Atlas", "Monaco", "Barcelona", "New York Red Bulls", "Leon", "Verona", "Atlas"]
  },
  {
    player: "Alexander Hleb",
    difficulty: 5,
    clubs: ["Stuttgart", "Arsenal", "Barcelona", "Birmingham City", "Wolfsburg", "Krylia Sovetov", "BATE Borisov", "Konyaspor", "Genclerbirligi"]
  },
  {
    player: "Kevin-Prince Boateng",
    difficulty: 5,
    clubs: ["Hertha BSC", "Tottenham Hotspur", "Dortmund", "Portsmouth", "AC Milan", "Schalke 04", "Las Palmas", "Eintracht Frankfurt", "Sassuolo", "Barcelona", "Fiorentina", "Besiktas", "Monza"]
  },
  {
    player: "Robbie Keane",
    difficulty: 5,
    clubs: ["Wolves", "Coventry City", "Inter Milan", "Leeds United", "Tottenham Hotspur", "Liverpool", "Celtic", "West Ham United", "LA Galaxy", "Aston Villa"]
  },
  {
    player: "Christian Vieri",
    difficulty: 5,
    clubs: ["Torino", "Pisa", "Ravenna", "Venezia", "Atalanta", "Juventus", "Atletico Madrid", "Lazio", "Inter Milan", "AC Milan", "Monaco", "Fiorentina"]
  },
  {
    player: "Luca Toni",
    difficulty: 5,
    clubs: ["Modena", "Empoli", "Fiorentzuola", "Treviso", "Vicenza", "Brescia", "Palermo", "Fiorentina", "Bayern Munich", "Roma", "Genoa", "Juventus", "Al Nasr", "Verona"]
  },
  {
    player: "Emmanuel Adebayor",
    difficulty: 5,
    clubs: ["Metz", "Monaco", "Arsenal", "Manchester City", "Real Madrid", "Tottenham Hotspur", "Crystal Palace", "Istanbul Basaksehir", "Olimpia"]
  },
  {
    player: "Craig Bellamy",
    difficulty: 5,
    clubs: ["Norwich City", "Coventry City", "Newcastle United", "Celtic", "Blackburn Rovers", "Liverpool", "West Ham United", "Manchester City", "Cardiff City"]
  },
  {
    player: "Peter Crouch",
    difficulty: 5,
    clubs: ["Tottenham Hotspur", "QPR", "Portsmouth", "Aston Villa", "Norwich City", "Southampton", "Liverpool", "Stoke City", "Burnley"]
  },
  {
    player: "Djibril Cissé",
    difficulty: 5,
    clubs: ["Auxerre", "Liverpool", "Marseille", "Sunderland", "Panathinaikos", "Lazio", "QPR", "Al-Gharafa", "Kuban Krasnodar", "Bastia"]
  },
  {
    player: "Lassana Diarra",
    difficulty: 5,
    clubs: ["Le Havre", "Chelsea", "Arsenal", "Portsmouth", "Real Madrid", "Anzhi Makhachkala", "Lokomotiv Moscow", "Marseille", "Al Jazira", "Paris Saint Germain"]
  },
  {
    player: "Hatem Ben Arfa",
    difficulty: 5,
    clubs: ["Lyon", "Marseille", "Newcastle United", "Hull City", "Nice", "Paris Saint Germain", "Rennes", "Valladolid", "Bordeaux", "Lille"]
  },
  {
    player: "Pepe Reina",
    difficulty: 5,
    clubs: ["Barcelona", "Villarreal", "Liverpool", "Napoli", "Bayern Munich", "AC Milan", "Aston Villa", "Lazio", "Villarreal", "Como"]
  },
  {
    player: "Ricardo Quaresma",
    difficulty: 5,
    clubs: ["Sporting CP", "Barcelona", "Porto", "Inter Milan", "Chelsea", "Besiktas", "Al-Ahli", "Kasimpasa", "Vitoria Guimaraes"]
  },
  {
    player: "Alvaro Morata",
    difficulty: 5,
    clubs: ["Real Madrid", "Juventus", "Real Madrid", "Chelsea", "Atletico Madrid", "Juventus", "Atletico Madrid", "AC Milan"]
  }
];